CREATE SCHEMA IF NOT EXISTS DATENBASIS;
SET SCHEMA DATENBASIS;

DROP TABLE IF EXISTS BERATER;
CREATE TABLE IF NOT EXISTS BERATER
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TYP VARCHAR(255) check (TYP in ('SACHBEARBEITER', 'SUPER_USER', 'ADMIN')),
	NAME VARCHAR(255) NOT NULL,
	VORNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	TELEFON VARCHAR(255) UNIQUE NOT NULL,
	ANWESENHEIT VARCHAR(255),
	BERATUNGSTHEMA BIGINT,
	PROFILBILD BLOB,
	AMTSART BIGINT NOT NULL,
	CREATION_BY VARCHAR(255),
	CREATION_ON TIMESTAMP,
	LASTUPDATE_BY VARCHAR(255),
	LASTUPDATE_ON TIMESTAMP
);

DROP TABLE IF EXISTS BERATUNGSTHEMEN_GEBIETE;
CREATE TABLE IF NOT EXISTS BERATUNGSTHEMEN_GEBIETE
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	BESCHREIBUNG VARCHAR(2000) NOT NULL,
	IMAGE_HEADER BLOB,
	IMAGE_PROFILE BLOB,
	CREATION_BY VARCHAR(255),
	CREATION_ON TIMESTAMP,
	LASTUPDATE_BY VARCHAR(255),
	LASTUPDATE_ON TIMESTAMP
);

DROP TABLE IF EXISTS LOGGING;
CREATE TABLE IF NOT EXISTS LOGGING
(
	REQUEST_ID UUID PRIMARY KEY,
	REQUEST_CALLERNAME VARCHAR(255) NOT NULL,
	REQUEST_TIMESTAMP TIMESTAMP,
	REQUEST_TYPE VARCHAR(255) NOT NULL,
	REQUEST_DATAOBJEKT VARCHAR(255) NOT NULL,
	REQUEST_FULLURL VARCHAR(255) NOT NULL,
	REQUEST_PAYLOAD CLOB,
	JOB_LOG CLOB,
	RESPONSE_STATUS VARCHAR(255) NOT NULL,
	RESPONSE_PAYLOAD CLOB,
	REPONSE_TIMESTAMP TIMESTAMP
);