/**
 * 
 */
{
  "items": [
    {
      "_archived": false,
      "_draft": false,
      "fristen": null,
      "antwort": "<p>Fahrzeuge dürfen auf öffentlichen Straßen nur in Betrieb gesetzt werden, wenn sie zum Verkehr zugelassen sind. Die Zulassung wird auf Antrag erteilt, wenn das Fahrzeug einem genehmigten Typ entspricht oder eine Einzelgenehmigung erteilt ist und eine dem Pflichtversicherungsgesetz entsprechende Kraftfahrzeug-Haftpflichtversicherung besteht. Die Zulassung erfolgt durch Zuteilung eines Kennzeichens, Abstempelung der Kennzeichenschilder und Ausfertigung einer Zulassungsbescheinigung durch die Zulassungsbehörde.</p>",
      "name": "Kraftfahrzeug anmelden",
      "zustandige-stellen": "<p>Verkehrsüberwachungsamt</p>",
      "vorgehensweise-und-detail": "<p>Nachweis über die Kraftfahrzeug-Haftpflichtversicherung:</p><p>Zum 01. März 2008 wurde in Deutschland die elektronische Versicherungsbestätigung (eVB) zum Abruf eingeführt.</p><p>Damit entfällt die Pflicht zur Vorlage einer Versicherungsbestätigung nach altem Muster (Deckungskarte). Die Versicherer teilen ihren Kunden stattdessen eine Versicherungsbestätigungs-Nr. (eVB, 7-stelliger alphanumerischer Code) mit. Mit Hilfe dieser eVB-Nummer kann die Zulassungsbehörde prüfen, ob eine verarbeitungsfähige Versicherungsbestätigung für den/die Halter/in hinterlegt wurde.</p><p>‍</p><p>KFZ-Zulassung nur noch mit Einzugsermächtigung für die Kraftfahrzeugsteuer:</p><p>Wer ein Fahrzeug neu zulässt oder ummeldet, muss eine Einzugsermächtigung für die Kfz-Steuer erteilen. Die Einzugsermächtigung für die Kfz-Steuer gilt nur für das zugelassene Fahrzeug und erlischt nach dessen Abmeldung.</p><p>Das bisherige Zahlungsverfahren über die Einzugsermächtigung wurde nunmehr europaweit vereinheitlicht. Daher ist eine Umstellung auf das SEPA-Lastschriftverfahren erfolgt. Statt Kontonummer und Bankleitzahl sind jetzt IBAN und BIC im Einsatz.</p><p>Die Verwaltung der Kraftfahrzeugsteuer, die bisher in dem Zuständigkeitsbereich der Finanzämter lag, wird seit 5. April 2014 von dem Hauptzollamt Ulm durchgeführt.</p><p>Weitere Informationen erhalten Sie unter www.zoll.de.</p><p>Durch die Umstellung auf das SEPA-Lastschriftverfahren muss im Regelfall bei jeder Zulassung ein SEPA-Lastschriftmandat zum Einzug der Kraftfahrzeugsteuer vorgelegt werden. Das für die Zulassungsbehörde Mainz gültige SEPA-Lastschriftmandat finden Sie im Abschnitt \"Formulare\" am Ende dieser Seite oder liegt in Papierform vor Ort bereit.</p><p>Anträge und Informationen zur Steuervergünstigung für ein Fahrzeug finden Sie unter www.zoll.de. Anträge auf Steuervergünstigung wegen Schwerbehinderung können bei Vorlage des Schwerbehindertenausweises (Original) im Rahmen eines Zulassungsvorganges bei der Zulassungsbehörde eingereicht werden.</p><p>‍</p><p>Rückständige Gebühren bei der Zulassungsbehörde:</p><p>Die Zulassung ist davon abhängig, dass alle rückständigen Gebühren, die im Zusammenhang mit der Zulassung angefallen sind, bezahlt wurden. Rückständige Gebühren können im Rahmen der Zulassung vor Ort beglichen werden.</p><p>‍</p><p>Umschreibung mit Kennzeichenmitnahme:</p><p>Seit dem 01.01.2015 ist bundesweit die Pflicht zur Umkennzeichnung bei Wohnsitzwechsel ohne Halterwechsel aufgehoben. Halter/in eines zugelassenen Fahrzeuges, die innerhalb von Deutschland umziehen, können auf Wunsch das Kennzeichen mitnehmen. Die Umschreibung des Fahrzeuges nach Mainz muss jedoch weiterhin erfolgen. Die erforderlichen Unterlagen für eine Umschreibung mit Kennzeichenmitnahme entnehmen Sie bitte der Dienstleistung \"Kraftfahrzeug ummelden (Umschreibung)\" im Abschnitt ähnliche Dienstleistungen .</p><p>‍</p><p>Rechtsgrundlagen:</p><p>• Fahrzeug-Zulassungsverordnung (FZV)</p><p>• Gebührenordnung über Maßnahmen im öffentlichen Straßenverkehr (GebOSt)</p><p>• § 5 Kraftfahrzeugsteuer-Durchführungsverordnung (KraftStDV)</p><p>• Straßenverkehrs-Zulassungs-Ordnung (StVZO)</p>",
      "zielgruppe": "<p>Halter von Kraftfahrzeugen</p>",
      "mehr-zu-diesem-thema": "<p>https://wkzneu.service24.rlp.de/Vorgangserfassung.aspx?ags=07315000</p><p>https://wkzneu.service24.rlp.de/Vorgangserfassung.aspx?ags=07315000</p>",
      "antwort-vorschau": "Fahrzeuge dürfen auf öffentlichen Straßen nur in Betrieb gesetzt werden, wenn sie zum Verkehr zugelassen sind. Die Zulassung wird auf Antrag erteilt, wenn das Fahrzeug einem genehmigten Typ entspricht oder eine Einzelgenehmigung erteilt ist und eine dem Pflichtversicherungsgesetz entsprechende Kraftfahrzeug-Haftpflichtversicherung besteht.",
      "slug": "kraftfahrzeug-anmelden",
      "zugehoriger-service-2": "581cad9f257cc18c5a30848d",
      "updated-on": "2016-11-05T17:53:23.153Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:53:23.153Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e1c937abac00612e61053"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Am 01.03.2007 ist die Verordnung zum Erlass und zur Änderung von Vorschriften über die Kennzeichnung emissionsarmer Kraftfahrzeuge in Kraft getreten. Die Verordnung gilt für Kraftfahrzeuge der Klassen M und N (für die Personen- und Güterbeförderung ausgelegte und gebaute Kraftfahrzeuge mit mindestens vier Rädern). Aufgrund dieser Verordnung werden die genannten Kraftfahrzeuge in die Schadstoffgruppen 1 bis 4 eingeteilt. Kraftfahrzeuge der Schadstoffgruppen 2 bis 4 erhalten Plaketten zur Kennzeichnung der Schadstoffgruppe. Die vier Schadstoffgruppen orientieren sich an den Abgasemissionsstufen von Dieselfahrzeugen (Euro 1 bis Euro 4 bei Pkw sowie Euro I bis Euro V und EEV bei Nutzfahrzeugen). Fahrzeuge mit zukünftigen Abgasstufen fallen in die beste Schadstoffgruppe und erhalten eine grüne Feinstaubplakette.</p><p>Die Verordnung schafft die Voraussetzungen für die Einführung von Umweltzonen mit emissionsabhängigen Fahrverboten. Durch die Kennzeichnungsverordnung selbst werden keine konkreten Umweltzonen oder Fahrverbote festgelegt. Dies kann durch die zuständigen Behörden in den Kommunen erfolgen, wenn die Luftqualitätsgrenzwerte überschritten werden, der Verkehr eine wichtige Ursache ist und die Einrichtung einer Umweltzone als Maßnahme im Luftreinhalteplan dieser Kommune festgelegt ist. In Umweltzonen, die durch Städte und Gemeinden eingerichtet werden, dürfen nur noch Fahrzeuge fahren, die gemäß der jeweiligen Ausschilderung an der Windschutzscheibe mit einer mit dem amtlichen Kennzeichen des Fahrzeugs versehenen Plakette zur Kennzeichnung der Schadstoffgruppe versehen sind.</p>",
      "fristen": "<p>Bearbeitungszeit:</p><p>Bei Vorsprache im Regelfall sofort, Wartezeit abhängig vom Publikumsandrang.</p>",
      "name": "Feinstaubplakette beantragen",
      "vorgehensweise-und-detail": "<p>In Mainz wurde die Umweltzone zum 01. Februar 2013 eingeführt. Entsprechend der Ausschilderung dürfen nur noch Fahrzeuge mit einer grünen Feinstaubplakette in die Umweltzone einfahren.</p><p>Folgende Kraftfahrzeuge dürfen ohne grüne Feinstaubplakette in die Umweltzone einfahren:</p><p>1. mobile Maschinen und Geräte,</p><p>2. Arbeitsmaschinen,</p><p>3. land- und forstwirtschaftliche Zugmaschinen,</p><p>4. zwei- und dreirädrige Kraftfahrzeuge,</p><p>5. Krankenwagen, Arztwagen mit entsprechender Kennzeichnung „Arzt Notfalleinsatz“ (gemäß § 52 Abs. 6 der Straßenverkehrs-Zulassungs-Ordnung),</p><p>6. Kraftfahrzeuge, mit denen Personen fahren oder gefahren werden, die außergewöhnlich gehbehindert, hilflos oder blind sind und dies durch die nach § 3 Abs. 1 Nr. 1 bis 3 der Schwerbehindertenausweisverordnung im Schwerbehindertenausweis eingetragenen Merkzeichen „aG“, „H“ oder „Bl“ nachweisen,</p><p>7. Fahrzeuge, für die Sonderrechte nach § 35 der Straßenverkehrs-Ordnung in Anspruch genommen werden können (z.B. Polizei, Feuerwehr),</p><p>8. Fahrzeuge nichtdeutscher Truppen von Nichtvertragsstaaten des Nordatlantikpaktes, die sich im Rahmen der militärischen Zusammenarbeit in Deutschland aufhalten, soweit sie für Fahrten aus dringenden militärischen Gründen genutzt werden,</p><p>9. zivile Kraftfahrzeuge, die im Auftrag der Bundeswehr genutzt werden, soweit es sich um unaufschiebbare Fahrten zur Erfüllung hoheitlicher Aufgaben der Bundeswehr handelt,</p><p>10. Oldtimer (gemäß § 2 Nr. 22 der Fahrzeug-Zulassungsverordnung), die ein H- oder 07er-Kennzeichen führen, sowie Fahrzeuge, die in einem anderen Mitgliedstaat der EU/EWR oder der Türkei zugelassen sind, wenn sie gleichwertige Anforderungen erfüllen.</p><p>‍</p><p>Beantragung:</p><p>•persönlich</p><p>•Vertretung durch Dritte/n</p><p>‍</p><p>Voraussetzungen:</p><p>• Emissionsschlüsselnummer des Fahrzeuges entspricht der Schadstoffgruppe 4</p><p>• Emissionsschlüsselnummer des Fahrzeuges entspricht nicht der Schadstoffgruppe 4, das Fahrzeug wurde jedoch mit einem entsprechenden Partikelminderungssystem nachgerüstet (Eintragung in der Zulassungsbescheinigung Teil I erforderlich)</p><p>‍</p><p>Unterlagen:</p><p>• Zulassungsbescheinigung Teil I bzw. Fahrzeugschein</p><p>‍</p><p>Gebühren:</p><p>• Feinstaubplakette: 6,60 Euro</p><p>‍</p><p>Zahlungsart: Bar / EC</p><p>‍</p><p>Rechtsgrundlagen:</p><p>35. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (35.BImSchV)</p><p>‍</p><p>Hinweise:</p><p>Weitere Ausgabestellen der Feinstaubplaketten sind alle für die Durchführung von Abgasuntersuchungen anerkannten Stellen (in Mainz z.B. DEKRA und TÜV-Prüfstellen).</p>",
      "zielgruppe": "<p>Halter von Kraftfahrzeugen</p>",
      "mehr-zu-diesem-thema": "<p>http://www.tuev-sued.de/auto_fahrzeuge/feinstaub-plakette</p><p>http://www.umwelt-plakette.de/foreign_cars.php?SID=lttn7q1gpece9sa2l33dcmc170</p>",
      "antwort-vorschau": "Am 01.03.2007 ist die Verordnung zum Erlass und zur Änderung von Vorschriften über die Kennzeichnung emissionsarmer Kraftfahrzeuge in Kraft getreten.",
      "slug": "feinstaubplakette-beantragen",
      "zugehoriger-service-2": "581caded16e8e0ee061f8225",
      "updated-on": "2016-11-05T18:09:35.713Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:48:17.084Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T18:11:00.558Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "zustandige-stellen": "<p>Verkehrsüberwachungsamt</p>",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e1b617abac00612e60f5f"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Schulpflichtig zum Schuljahr 2017/18 sind alle Kinder, die bis zum 31. August 2017 das 6. Lebensjahr vollenden.Die Anmeldung der Kann-Kinder (6. Geburtstag ab Anfang September 2017) erfolgt grundsätzlich im Februar des darauffolgenden Jahres in den jeweiligen staatlichen Grundschulen nach vorheriger telefonischer Terminvereinbarung.Die schulpflichtigen und die Kann-Kinder sind in der zuständigen Grundschule anzumelden (alle Grundschulen haben eigene Schulbezirke).</p><p>‍</p><p>Bei Zuzug nach Mainz und damit verbundenem Schulwechsel:</p><p>- zunächst sind die entsprechenden Schulen selbst und unmittelbar zu kontaktieren, um sich dort zu bewerben- dies bedeutet, dass sich Eltern mit ihren Kindern direkt (ohne Beteiligung des Schulamtes) bei der jeweiligen Schule bewerben- bei weiteren pädagogischen Fragen ist die Aufsichts- und Dienstleistungsdirektion zu kontaktieren.</p>",
      "name": "Schulanmeldung",
      "zustandige-stellen": "<p>Schulamt</p>",
      "vorgehensweise-und-detail": "<p>Unterlagen:</p><p>Bei der Anmeldung von Schulneulingen für die 1. Klassenstufe (Einschulung) ist die Geburtsurkunde oder das Familienstammbuch vorzulegen.</p><p>‍</p><p>Hinweise:</p><p>Für die Aufnahme von Schülerinnen und Schülern ist die jeweilige Schulleitung zuständig.</p><p>‍</p><p>Bei weiteren Fragen kann die Aufsichts- und Dientsleistungsdirektion (ADD) kontaktiert werden:</p><p>Aufsichts- und Dienstleistungsdirektion</p><p>Außenstelle Neustadt a.d.W.</p><p>Friedrich-Ebert-Str. 14</p><p>67433 Neustadt a.d.W.</p><p>Tel: +49(6321) 99-0</p><p>Die ADD ist nur für die staatlichen Schulen zuständig.</p>",
      "zielgruppe": "<p>Familien mit schulpflichtigen Kindern</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/produkte/schulamt/100140100000027504.php.media/112413/Info-Blatt_fuer_die_Eltern_der_4._Grundschulkl._2017_18.pdf</p><p>https://www.mainz.de/vv/produkte/schulamt/100140100000027504.php.media/112414/Oeff_Bekanntmachung_Anmeldetermine_Schulneulinge_2017_18.pdf</p>",
      "antwort-vorschau": "Schulpflichtig zum Schuljahr 2017/18 sind alle Kinder, die bis zum 31. August 2017 das 6. Lebensjahr vollenden.",
      "slug": "schulanmeldung",
      "zugehoriger-service-2": "581cafb3cc2d720a376b012c",
      "updated-on": "2016-11-05T17:41:42.953Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:41:42.953Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e19d67abac00612e60c1b"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Für das Mittagessen ist ein Eigenanteil von zurzeit 3,00 Euro pro Essen von den Eltern zu übernehmen.</p><p>‍</p><p>Kinder, deren Eltern Kinderzuschlag oder Wohngeld beziehen oder leistungsberechtigt nach dem SGB II, dem SGB XII oder dem AsylbLG sind, haben einen Anspruch nach dem Bildungs- und Teilhabepakt.</p><p>‍</p><p>Für Geringverdiener besteht ein Härtefonds.</p><p>- Bei Vorliegen der Voraussetzungen beträgt für diese Personengruppen der Eigenanteil lediglich 1,00 € pro Essen.</p><p>- Die entsprechenden Anträge können bei der Stadtverwaltung Mainz, 40 – Schulamt gestellt werden.</p>",
      "name": "Mittagsverpflegung",
      "zustandige-stellen": "<p>Schulamt</p>",
      "vorgehensweise-und-detail": "<p>An Ganztagsschulen wird eine Mittagsverpflegung für die Schülerinnen und Schüler angeboten. Die von den städtischen Gremien beschlossenen Empfehlungen des Arbeitskreises vom 27.11.2007 sind seitdem Basis für die Ausschreibung der Mittagessensversorgung. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Die Verpflegung erfolgt auf der Grundlage der „Qualitätsstandards für die Schülerverpflegung“ der Deutschen Gesellschaft zur Ernährung (DGE). Die Anforderungen der Stadt Mainz gehen allerdings noch über diese Anforderungen hinaus: - täglich wird Rohkost, Salat und Obst angeboten - täglich werden mindestens 0,4 ltr. Getränk zum Essen angeboten (nach DGE sind nur 0,2 ltr vorgesehen) - die Warmhaltezeit des Essens sollte 1 Stunde nicht überschreiten (nach DGE sind 2 bis 3 Stunden erlaubt). &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Durch diese Festlegung auf max. 1 Stunde kommen nur die beiden Verpflegungsarten „vorgegarte Tiefkühlkost“ oder „Cook &amp; Chill“ in Frage. Bei beiden Verpflegungsarten werden jedoch die Beilagen wie Reis, Nudeln oder Kartoffeln sowie die Rohkost oder Salate vor Ort frisch zubereitet. Zur Ausschreibung können sich die Schulen für eine Verpflegungsart entscheiden. </p>",
      "zielgruppe": "<p>Familien mit schulpflichtigen Kindern</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Haertefondsantrag_2016-2017.pdf</p>",
      "antwort-vorschau": "Mittagsverpflegung",
      "slug": "mittagsverpflegung",
      "zugehoriger-service-2": "581cb10c16e8e0ee061f8ae1",
      "updated-on": "2016-11-05T17:34:18.205Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:34:18.205Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e181a910be8fb11c094ac"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Versammlungen und Demonstrationen werden vom Rechts- und Ordnungsamt genehmigt</p>",
      "name": "Versammlungen / Demonstrationen",
      "zustandige-stellen": "<p>Rechts- und Ordnungsamt </p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Aufnahmevordruck-Demonstrationen-Jung.pdf</p><p>https://www.mainz.de/vv/merkblatt-demonstration.pdf</p><p>‍</p>",
      "antwort-vorschau": "Versammlungen und Demonstrationen werden vom Rechts- und Ordnungsamt genehmigt",
      "slug": "versammlungen-demonstrationen",
      "zugehoriger-service-2": "581df932b69ed76343e78cec",
      "updated-on": "2016-11-05T17:16:21.738Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:16:21.738Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e13e5910be8fb11c090bd"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Information der Öffentlichkeit in Bezug auf Verstöße gegen das Lebensmittel- und Futtermittelrecht nach § 40 Abs. 1 a LFGB.</p><p>Gemäß § 40 Abs. 1 a Lebensmittel- und Futtermittelgesetz (LFGB) sind Behörden seit dem 01.09.2012 dazu verpflichtet, bei durch Tatsachen begründeten Verdacht die Öffentlichkeit zu informieren, dass </p><p>Gesetzlich vorgeschriebene Grenzwerte, Höchstgehalte oder Höchstmengen überschritten wurden. Gegen hygienische Anforderungen in nicht nur unerheblichem Ausmaß oder wiederholt verstoßen worden ist.Gegen sonstige Vorschriften im Anwendungsbereich des LFGB verstoßen worden ist, die dem Schutz der Verbraucherinnen und Verbraucher vor Gesundheitsgefährdungen oder vor Täuschung dienen.</p>",
      "name": "Lebensmittelüberwachung und Verbraucherschutz",
      "zustandige-stellen": "<p>Rechts- und Ordnungsamt</p>",
      "vorgehensweise-und-detail": "<p>Nähere Informationen zu Verstößen nach § 40 Abs. 1 a LFGB finden Sie unter Downloads. Mitteilungs- und Übermittlungspflichten eines Lebensmittel- oder Futtermittelunternehmers über Untersuchungsergebnisse zu gesundheitlich nicht erwünschten Stoffen gemäß § 44a Lebensmittel- und Futtermittelgesetzbuch (LFGB) Ein Lebensmittelunternehmer oder ein Futtermittelunternehmer ist verpflichtet, unter Angabe seines Namens und seiner Anschrift ihm vorliegende Untersuchungsergebnisse über Gehalte an gesundheitlich nicht erwünschten Stoffen wie Pflanzenschutzmitteln, Stoffen mit pharmakologischer Wirkung, Schwermetallen, Mykotoxinen und Mikroorganismen in und auf Lebensmitteln oder Futtermitteln nach näherer Bestimmung der entsprechenden Rechtsverordnung den zuständigen Behörden mitzuteilen, sofern sich eine solche Verpflichtung nicht bereits aus anderen Rechtsvorschriften ergibt. Weitere Informationen und Vordrucke dazu finden Sie auf der Website des Landesuntersuchungsamtes.</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Zustaendigkeiten_Lebensmittelkontrolle.pdf</p><p>https://www.mainz.de/vv/merkblatt-ortsveraenderliche-betriebsstaetten.pdf</p><p>https://www.mainz.de/vv/Lebensmittel_Verbraucherschutz.pdf</p><p>https://www.mainz.de/vv/Muster-Tabelle-para-40Abs1aLFGB.pdf</p><p>‍</p>",
      "antwort-vorschau": "Information der Öffentlichkeit in Bezug auf Verstöße gegen das Lebensmittel- und Futtermittelrecht nach § 40 Abs. 1 a LFGB.",
      "slug": "lebensmitteluberwachung-und-verbraucherschutz",
      "zugehoriger-service-2": "581df7917abac00612e5dd84",
      "updated-on": "2016-11-05T17:13:42.367Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:13:42.367Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e13464869c31f66b98c90"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Deutsche Staatsbürger/innen sind ab dem 16. Lebensjahr sind verpflichtet, einen Ausweis zu besitzen (Ausnahme: Wenn bereits ein gültiger Reisepass vorhanden ist).</p>",
      "fristen": "<p>Der Ausweis kann ca. 3 Wochen nach Antragstellung abgeholt werden, es findet keine Benachrichtigung seitens der Bundesdruckerei statt.</p><p>Ca. eine Woche nachdem des Schreiben bezgl. des PIN-Briefs eingegangen ist, kann der Personalausweis abgeholt werden.</p>",
      "name": "Personalausweis beantragen",
      "zustandige-stellen": "<p>Bürgeramt</p>",
      "vorgehensweise-und-detail": "<p>Seit dem 01.11.2010 gibt es den Personalausweis nur noch im neuen Scheckkartenformat.</p><p>‍</p><p>Beantragung:</p><p>• persönlich (wegen der Unterschriftsleistung und ggf. Fingerabdrücke)</p><p>• in dringenden Fällen kann ein vorläufiger Personalausweis ausgestellt werden (in Verbindung mit der Beantragung eines endgültigen Personalausweises)</p><p>‍</p><p>Gültigkeit:</p><p>• Personen unter 24 Jahre: 6 Jahre gültig</p><p>• Personen über 24 Jahre: 10 Jahre gültig</p><p>&nbsp;</p><p>Voraussetzungen:</p><p>- Der Antragsteller muss deutscher Staatsbürger sein</p><p>- Altersmäßig gibt es keine Begrenzung</p><p>‍</p><p>Unterlagen:</p><p>- alter Personalausweis oder Reisepass</p><p>- 1 biometrisches Lichtbild (nicht älter als 6 Monate, schwarz-weiß oder bunt)</p><p>- Bei Personen mit einem gesetzlichen Betreuer zusätzlich: </p><p>• &nbsp;Urkunde des Betreuers, Generalvollmacht o.ä. Nachweis</p><p>‍</p><p>Gebühren:</p><p>Hauptwohnung in Mainz = zuständige Behörde</p><p>• 22,80 Euro (unter 24 Jahre)</p><p>• 28,80 Euro (über 24 Jahre)</p><p>• Ausweissichthüllen: 2,00 Euro</p><p>‍</p><p>Zahlungsart:&nbsp;Bar / EC</p><p>‍</p><p>Rechtsgrundlagen:</p><p>- Personalausweisgesetz</p><p>- Passgesetz</p>",
      "mehr-zu-diesem-thema": "<p>http://www.auswaertiges-amt.de/DE/Startseite_node.html</p>",
      "antwort-vorschau": "Deutsche Staatsbürger/innen sind ab dem 16. Lebensjahr sind verpflichtet, einen Ausweis zu besitzen.",
      "slug": "personalausweis-beantragen",
      "zugehoriger-service-2": "581cb15f16e8e0ee061f8cd7",
      "updated-on": "2016-11-05T17:09:31.714Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:09:31.714Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e124bfe18a07e43932faf"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Wer aus einem Nicht-EU- oder Nicht-EWR-Staat kommt und in Deutschland &nbsp;arbeiten möchte, braucht eine Aufenthaltserlaubnis sowie eine damit verbundene Arbeitserlaubnis. Hierzu muss das Formblatt „Antrag auf Zustimmung zu einer Beschäftigung“ ausgefüllt (gegebenenfalls mit Unterstützung des zukünftigen Arbeitgebers) und bei der Ausländerbehörde eingereicht werden. Nach Rücksprache mit der Bundesagentur für Arbeit, die der Erwerbstätigkeit zustimmen muss, erhalten Sie von uns dann Ihre Aufenthalts-erlaubnis. Auf dieser finden Sie dann auch Ihre Arbeitserlaubnis mit allen Informationen darüber, welche Erwerbstätigkeiten Sie ausüben dürfen.</p>",
      "fristen": "<p>Bearbeitungszeit ca. 6 Wochen</p>",
      "name": "Arbeitserlaubnis",
      "zustandige-stellen": "<p>Bürgeramt</p>",
      "vorgehensweise-und-detail": "<p>Aufenthaltstitel zur Arbeitsplatzsuche:</p><p>Bei Ausländern mit einem abgeschlossenem Hochschulstudium und nachweislich gesichertem Lebensunterhalt, können die deutschen Auslandsvertretungen ein Visum zur Arbeitsplatzsuche in Deutschland ausstellen. Dieses Visum ist maximal sechs Monate gültig und ist nicht gleichzeitig eine Arbeitserlaubnis. Wurde ein potentieller Arbeitgeber gefunden, muss die entsprechende Aufenthaltserlaubnis mit Arbeitserlaubnis bei der Ausländerbehörde beantragt werden.</p><p>Staatsangehörige von Australien, Neuseeland, Israel, Japan, Kanada, der Republik Korea und den Vereinigten Staaten von Amerika können ohne Visum in die Bundesrepublik Deutschland einreisen und unter Abgabe des Formblattes „Antrag auf Zustimmung zu einer Beschäftigung“ &nbsp;bei der Ausländerbehörde die Aufenthaltserlaubnis beantragen.</p><p>‍</p><p>Staatsangehörige der EU-Mitgliedstaaten benötigen grundsätzlich keine Arbeitserlaubnis.</p><p>Nicht-EU-Bürger, die in Deutschland einer Erwerbstätigkeit nachgehen möchten</p><p>• benötigen hierfür grundsätzlich eine Arbeitserlaubnis</p><p>• auch für die Tätigkeit als Au-Pair ist dies notwendig</p><p>‍</p><p>Die Ersterteilung sowie eine Verlängerung erfolgt nach:</p><p>• Antragstellung beim zuständigen Sachbearbeiter</p><p>• nach Einzelfallprüfung wird ggf. die Bundesagentur für Arbeit beteiligt</p><p>‍</p><p>Unterlagen:</p><p>• ausgefüllten Antrag</p><p>• Arbeitsvertrag</p><p>• Stellenbeschreibung vom Arbeitgeber</p><p>‍</p><p>Gebühren:&nbsp;Es fallen keine Gebühren an</p><p>‍</p><p>Rechtsgrundlagen:</p><p>§§ 17, 18, 18c, 19a, 38a AufenthG</p>",
      "zielgruppe": "<p>Personen aus einem Nicht-EU- oder Nicht-EWR-Staat</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Antrag_auf_Arbeitserlaubnis__Sept._2016_.doc</p>",
      "antwort-vorschau": "Wer aus einem Nicht-EU- oder Nicht-EWR-Staat kommt und in Deutschland arbeiten möchte, braucht eine Aufenthaltserlaubnis sowie eine damit verbundene Arbeitserlaubnis.",
      "slug": "arbeitserlaubnis",
      "zugehoriger-service-2": "581caed5257cc18c5a308a83",
      "updated-on": "2016-11-05T17:04:55.325Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T17:04:55.325Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e1137b69ed76343e7c2b5"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Ausländische Mitbürger können unter bestimmten Voraussetzungen auf Antrag die deutsche Staatsangehörigkeit erwerben (Einbürgerung)</p>",
      "name": "Staatsangehörigkeit beantragen",
      "zustandige-stellen": "<p>Bürgeramt</p>",
      "vorgehensweise-und-detail": "<p>Voraussetzungen:</p><p>- Niederlassungs- oder Aufenthaltserlaubnis, Aufenthaltsrecht als Unions- oder Schweizerbürger</p><p>- mindestens acht Jahre Inlandsaufenthalt</p><p>- Unterhaltsfähigkeit</p><p>- ausreichende Deutschkenntnisse</p><p>- staatsbürgerliches Grundwissen</p><p>- keine Mehrstaatigkeit</p><p>- nicht bestraft</p><p>- Bekenntnis zur freiheitlich demokratischen Grundordnung unseres Grundgesetzes</p><p>‍</p><p>Unterlagen:</p><p>- Antrag (wird bei der persönlichen Vorsprache ausgehändigt)</p><p>‍</p><p>Gebühren:</p><p>- Einbürgerung i.d.R.: 255,00 Euro</p>",
      "zielgruppe": "<p>Ausländische Mitbürger</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Fragen_und_Antworten_zur_Einbuergerung_April2016.pdf</p>",
      "antwort-vorschau": "Ausländische Mitbürger können unter bestimmten Voraussetzungen auf Antrag die deutsche Staatsangehörigkeit erwerben (Einbürgerung).",
      "slug": "staatsangehorigkeit-beantragen",
      "zugehoriger-service-2": "581ca76b8a3443f84a3b40d5",
      "updated-on": "2016-11-05T16:59:31.034Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:59:31.034Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0ff37abac00612e6043b"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>‍Bei einer Änderung des Familien- und/oder Vornamens &nbsp;- die nicht aufgrund einer Eheschließung oder Scheidung erfolgt &nbsp;- muss eine öffentlich-rechtliche Namensänderung beantragt werden.</p><p>Eine öffentlich-rechtliche Namensänderung dient ausschließlich dazu erhebliche Unzuträglichkeiten zu beseitigen, die sich im Einzelfall bei der Führung des nach bürgerlichem Recht zu tragenden Namens nachvollziehbar und nachweisbar ergeben.</p>",
      "name": "Namensänderung",
      "zustandige-stellen": "<p>Bürgeramt</p>",
      "vorgehensweise-und-detail": "<p>Die Gründe für die Namensänderung sind im Antrag ausführlich darzulegen.</p><p>‍</p><p>Für eine beschränkt geschäftsfähige Person stellt den Antrag:</p><p>- der gesetzliche Vertreter (Vater, Mutter, Vormund, Betreuer)</p><p>- ein Vormund bedarf hierzu der Genehmigung des Familiengerichts</p><p>- ein Betreuer des Betreuungsgerichts</p><p>Eine beschränkt geschäftsfähige Person, die das 16. Lebensjahr vollendet hat, ist vom Familien- oder Betreuungsgericht zum Antrag anzuhören. Die Genehmigung des Gerichts und der Nachweis über das Ergebnis der gerichtlichen Anhörung des Antragstellers sind dem Antrag beizufügen</p><p>‍</p><p>Voraussetzungen:</p><p>- Namensänderungen können nur durchgeführt werden für:</p><p>• &nbsp;Deutsche im Sinne des Grundgesetzes</p><p>• &nbsp;Staatenlose, heimatlose Ausländer, ausländische Flüchtlinge oder Asylberechtigte</p><p>- ein wichtiger Grund muss vorliegen</p><p>‍</p><p>Unterlagen:</p><p>Die Unterlagen sind jeweils im Original einzureichen. Alle Antragsunterlagen verbleiben grundsätzlich in der Behörde. Die vorgelegten Originalunterlagen werden nach erfolgter Beglaubigung der Kopien zurückgegeben.</p><p>Im Einzelfall können zur Antragsbearbeitung weitere Unterlagen und Nachweise erforderlich werden.</p><p>‍</p><p>- Nachweis: &nbsp;(z. B. Staatsangehörigkeitsausweis, Reisepass, Reiseausweis, Personalausweis,Kinderausweis):</p><p>• &nbsp;dass der Antragsteller entweder Deutscher im Sinne des Art. 116 Abs. 1 des Grundgesetzes &nbsp;oder</p><p>• &nbsp;staatenlos,</p><p>• &nbsp;heimatloser Ausländer,</p><p>• &nbsp;ausländischer Flüchtling,</p><p>• &nbsp;Asylberechtigter ist</p><p>- Der Antrag muss eine Erklärung darüber enthalten, ob schon früher eine Änderung des Namens beantragt wurde, gegebenenfalls wann und bei welcher Behörde</p><p>- Der Antragsteller muss ferner erklären, dass ihm bekannt ist, dass die Namensänderung bzw. die Ablehnung oder Zurücknahme des Antrages gebührenpflichtig ist</p><p>- Spätaussiedlerbescheinigung nach § 15 BVFG bzw. Vertriebenenausweis (bei Spätaussiedlern und Vertriebenen)</p><p>- Eine beglaubigte Abschrift des Geburteneintrags für den Antragsteller sowie für alle Personen, auf die sich die Änderung des Familiennamens erstrecken soll; die Urkunden müssen neueren Datums sein</p><p>- Falls der Antragsteller verheiratet ist oder war, die Eheurkunde. </p><p>- Bei einer Namensänderung aus familienrechtlichen Gründen sind auch Geburts- und Eheurkunden der Familienangehörigen vorzulegen, deren Namen der Antragsteller anzunehmen wünscht. </p><p>- Für Personen, die das vierzehnte Lebensjahr vollendet haben, ein Führungszeugnis nach § 30 Abs. 5 des Bundeszentralregistergesetzes (bei der zuständigen Meldebehörde zu beantragen; das Führungszeugnis wird von der ausstellenden Behörde direkt der Namensänderungsbehörde übersandt).</p><p>‍</p><p>Gebühren: Es fallen unterschiedliche Gebühren an, Zahlungsart:&nbsp;Bar / EC</p>",
      "zielgruppe": "<p>deutsche Staatsbürger, Staatenlose, heimatlose Ausländer, ausländische Flüchtlinge oder Asylberechtigte</p>",
      "mehr-zu-diesem-thema": "<p>http://www.mainz.de/verwaltung-und-politik/buergerservice-online/buergeramt-online-terminvereinbarung.php</p>",
      "antwort-vorschau": "‍Bei einer Änderung des Familien- und/oder Vornamens - die nicht aufgrund einer Eheschließung oder Scheidung erfolgt - muss eine öffentlich-rechtliche Namensänderung beantragt werden.",
      "slug": "namensanderung",
      "zugehoriger-service-2": "581ca7b65d7e0501760b8486",
      "updated-on": "2016-11-05T16:56:35.390Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:56:35.390Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0f43fe18a07e43932eac"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Ökologisch orientierte Stadtentwicklung bündelt umweltrelevante Informationen verschiedener Bereiche und Fachämter, z.B. Bodenschutz, Luftreinhaltung, Arten- und Biotopschutz, Lärmschutz, Wasserschutz und wertet diese aus. Auf dieser Basis werden Leitlinien und Empfehlungen formuliert, wie sich Stadtentwicklung innerhalb eines ökologisch verträglichen Rahmens, d.h. unter größtmöglicher Schonung der natürlichen Ressourcen und geringst möglicher Belastung von Mensch und Umwelt vollziehen kann.</p>",
      "name": "Ökologisch orientierte Stadtentwicklung",
      "zustandige-stellen": "<p>Amt für Stadtentwicklung, Statistik und Wahlen</p>",
      "mehr-zu-diesem-thema": "<p>www.mainz.de/agenda21</p>",
      "antwort-vorschau": "Ökologisch orientierte Stadtentwicklung bündelt umweltrelevante Informationen verschiedener Bereiche und Fachämter.",
      "slug": "okologisch-orientierte-stadtentwicklung",
      "zugehoriger-service-2": "581dfa45fe18a07e43931cd2",
      "updated-on": "2016-11-05T16:48:17.480Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:48:17.480Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0d517abac00612e60389"
    },
    {
      "_archived": false,
      "_draft": false,
      "mehr-zu-diesem-thema": null,
      "antwort": "<p>Bei Projekten mit raumbedeutsamen Auswirkungen wird ein Raumordnungsverfahren von der oberen Landesplanungsbehörde durchgeführt. </p><p>Die Träger öffentlicher Belange und damit die Gemeinden die von den Auswirkungen betroffen sein können, werden im Laufe des Verfahrens beteiligt und angehört. </p><p>Dabei geht es in erster Linie um Projekte auf dem Gebiet der Stadt Mainz, die der Pflicht zu einem Raumordnungsverfahren unterliegen. </p><p>Die Koordination der Stellungnahmen der einzelnen Fachämter wird im Amt für Stadtentwicklung, Statistik und Wahlen vorgenommen.</p>",
      "name": "Planfeststellungsverfahren/Raumordnungsverfahren",
      "zustandige-stellen": "<p>Amt für Stadtentwicklung, Statistik und Wahlen</p>",
      "vorgehensweise-und-detail": "<p>Raumordnerische Verfahren werden von der Struktur- und Genehmigungsdirektion Süd (früher Bezirksregierung) durchgeführt, Planfeststellungsverfahren von den jeweiligen Fachbehörden des Landes und Bundes (z.B. Landesstraßenverwaltung).</p><p>Die Stadt Mainz erteilt Auskünfte über raumordnerische Verfahren und Planfeststellungsverfahren, welche das Gebiet der Stadt Mainz betreffen oder an denen die Stadt Mainz beteiligt wird. Die Planunterlagen werden bei der Stadt öffentlich zur Einsichtnahme ausgelegt.</p>",
      "zielgruppe": "<p>Bauherren</p>",
      "antwort-vorschau": "Bei Projekten mit raumbedeutsamen Auswirkungen wird ein Raumordnungsverfahren von der oberen Landesplanungsbehörde durchgeführt.",
      "slug": "planfeststellungsverfahren-raumordnungsverfahren",
      "zugehoriger-service-2": "581df9d67abac00612e5e351",
      "updated-on": "2016-11-05T16:46:38.718Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:46:38.718Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0cee4869c31f66b981ea"
    },
    {
      "_archived": false,
      "_draft": false,
      "fristen": null,
      "mehr-zu-diesem-thema": null,
      "antwort": "<p>Hilfe zum Lebensunterhalt nach dem SGB XII erhalten Personen, die nicht auf Dauer erwerbsunfähig sind (z. B. eine befristete Erwerbsunfähigkeitsrente erhalten) und ihren Lebensunterhalt nicht aus eigenen Mitteln und Kräften bestreiten können.</p><p>Weitere Voraussetzung ist, dass der Lebensunterhalt nicht (vollständig) aus eigenem Einkommen und Vermögen bestritten werden kann. Das Einkommen und Vermögen des nicht getrennt lebenden Ehegatten oder Lebenspartner sowie des Partners einer eheähnlichen Gemeinschaft wird, soweit es den Eigenbedarf übersteigt, ebenfalls berücksichtigt.</p><p>Die Höhe der Hilfe zum Lebensunterhalt kann vorab nicht abgeschätzt werden, da eine individuelle Berechnung erfolgt.</p><p>Grundsätzlich umfassen die Leistungen:</p><p>- den maßgebenden Regelsatz</p><p>- angemessene Aufwendungen für Unterkunft und Heizung</p><p>- Übernahme von Kranken- und Pflegeversicherungsbeiträgen</p><p>- Mehrbedarfe nach § 30 SGB XII</p>",
      "name": "Hilfe zum Lebensunterhalt",
      "zustandige-stellen": "<p>Amt für soziale Leistungen</p>",
      "vorgehensweise-und-detail": "<p>Vor der Antragstellung:</p><p>Nehmen Sie bitte telefonisch Kontakt mit der zuständigen Sachbearbeiterin bzw. dem zuständigen Sachbearbeiter des Amtes für soziale Leistungen auf. Bei diesem Erstkontakt werden Ihnen auch die notwendigen Unterlagen genannt sowie ein Antrag zur Verfügung gestellt.</p><p>Persönliche Vorsprachen sind nur nach vorheriger Terminvereinbarung möglich.</p>",
      "zielgruppe": "<p>Personen, die nicht auf Dauer erwerbsunfähig sind</p>",
      "antwort-vorschau": "Hilfe zum Lebensunterhalt nach dem SGB XII erhalten Personen, die nicht auf Dauer erwerbsunfähig sind (z. B. eine befristete Erwerbsunfähigkeitsrente erhalten) und ihren Lebensunterhalt nicht aus eigenen Mitteln und Kräften bestreiten können.",
      "slug": "hilfe-zum-lebensunterhalt",
      "zugehoriger-service-2": "581caf49b0231b7f5a75b503",
      "updated-on": "2016-11-05T16:43:59.517Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:43:59.517Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0c4f7abac00612e6034e"
    },
    {
      "_archived": false,
      "_draft": false,
      "fristen": null,
      "antwort": "<p>Die Wohnraumförderung des Amtes für soziale Leistungen ist im Verwaltungsbereich der Stadt Mainz zuständig für die</p><p>a.) Förderprogramme des Landes Rheinland-Pfalz</p><p>Eigentumsmaßnahmen:</p><p>- Neubau, Ausbau, Umbau, Umwandlung, Erweiterung und Ankauf einer Wohnung im Bestand</p><p>- Modernisierung von eigengenutztem und vermietetem Wohnraum</p><p>‍</p><p>Mietwohnungsbau: </p><p>- Neubau von Wohnungen für Personen mit geringem Einkommen und einem Einkommen von nicht mehr als 60 v.H. über &nbsp; der Einkommensgrenze</p><p>- Erwerb von allgemeinen Belegungs- und Benennungsrechten,</p><p>- Schaffung von Wohnraum zur Einrichtung von Wohngruppen und Wohngemeinschaften für ältere Menschen und </p><p> &nbsp;Menschen mit Unterstützungsbedarf</p><p>- Errichtung von Studierendenwohnheime,- Förderung von Wohnraum für Flüchtlinge und Asylbewerber</p><p>‍</p><p>b.) Förderprogramme der Stadt Mainz </p><p>- Förderung von Wohneigentum für kinderreiche Haushalte</p><p>- Förderung des Baus von Mietwohnraum für kinderreiche Haushalte</p><p>- Mietsubventionen für wohnberechtigte Personenkreise</p>",
      "name": "Wohnraumförderung",
      "zustandige-stellen": "<p>Amt für soziale Leistungen</p>",
      "vorgehensweise-und-detail": "<p>Voraussetzungen:</p><p>Für den ersten Überblick zu den Förderkriterien der Landesförderung stellt die Investitions- und Strukturbank Rheinland-Pfalz (ISB) auf ihrer Internetseite entsprechende Informationsbroschüren zur Verfügung. Für detaillierte Informationen zu den Förderprogrammen des Landes und der Stadt Mainz besteht die Möglichkeit eines persönlichen Beratungsangebotes bei der zuständigen Wohnraumförderstelle der Stadt Mainz unter nachfolgenden Kontaktdaten zu vereinbaren.</p><p>‍</p><p>‍</p><p>Unterlagen:</p><p>Zu einem Vorgespräch sind bautechnische/-wirtschaftliche Unterlagen, einkommensbezogene Nachweise, unverbindliche Finanzierungsdarstellung mit Eigenkapitalangabe vorzulegen. Erst nach dem Vorgespräch können die benötigten Unterlagen konkretisiert werden.</p><p>‍</p><p>Rechtsgrundlagen:</p><p>in den jeweils gültigen Fassungen u.a.:</p><p>- Landeswohnraumförderungsgesetz (LWoFG), </p><p>- Verwaltungsvorschriften zu den Jahresförderprogrammen des Landes Rheinland-Pfalz</p><p>‍</p><p>Hinweise:</p><p>Aktuelle Informationen, Antragsunterlagen und Auskünfte zu den Förderkonditionen der Landesförderprogramme können auf der Internetseite der Investitions- und Strukturbank Rheinland-Pfalz (ISB) abgerufen werden.</p><p>Die Wohnraumförderung der Stadt Mainz ist ausschließlich für Fördermaßnahmen, deren Bauort innerhalb des Verwaltungsbereichs der Stadt Mainz liegt. Für Fördermaßnahmen außerhalb der Stadt Mainz sind die entsprechenden Verbands-, Kreis- oder Stadtverwaltungen zuständig.</p>",
      "zielgruppe": "<p>Bauherren</p>",
      "mehr-zu-diesem-thema": "<p>https://fm.rlp.de/de/themen/bauen-und-wohnen/wohnraumfoerderung/</p><p>http://isb.rlp.de/de/wohnraum</p><p>‍</p>",
      "antwort-vorschau": "Die Wohnraumförderung ist izuständig für die Förderprogramme des Landes Rheinland-Pfalz (Eigentumsmaßnahmen, Mietwohnungsbau uvm.).",
      "slug": "wohnraumforderung",
      "zugehoriger-service-2": "581cac4c257cc18c5a3081c6",
      "updated-on": "2016-11-05T16:41:31.130Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:41:31.130Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0bbbfe18a07e439329ae"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Wohngeld gibt es als Mietzuschuss für Mieterinnen und Mieter oder als Lastenzuschuss für Eigentümer einer Wohnung/ eines Hauses.</p><p>‍</p><p>Das Wohngeld richtet sich nach:</p><p>1. der Anzahl der zu berücksichtigenden Haushaltsmitglieder</p><p>2. der zu berücksichtigenden Miete (bei Mietern) bzw. Belastung (bei Eigentümern) und</p><p>3. dem Gesamteinkommen</p>",
      "fristen": "<p>- Wohngeld wird von Beginn des Monats an gewährt, in dem der Antrag gestellt wird.</p><p>- Zur Fristwahrung reicht zunächst ein formloser Antrag, dem aber der formelle Antrag mit Vordruck folgen muss.</p><p>- Die Bewilligung erfolgt in der Regel für zwölf Monate.</p><p>- Bearbeitungszeit: In der Regel innerhalb von zwei Monaten</p>",
      "name": "Wohngeld beantragen",
      "zustandige-stellen": "<p>Amt für soziale Leistungen</p>",
      "vorgehensweise-und-detail": "<p>Die Antragstellung erfolgt schriftlich (gilt für Erstanträge und Wiederholungsanträge). Anträge sind erhältlich:</p><p>- in allen Ortsverwaltungen</p><p>- an der Rathauspforte</p><p>- an der Information im Stadthaus</p><p>- im 2. Stock im Stadthaus (Wohngeldbehörde)</p><p>‍</p><p>Die ausgefüllten Anträge können </p><p>- per Post oder Fax dem Amt für soziale Leistungen zugesendet werden</p><p>- an der Information im Stadthaus abgegeben werden (bitte im verschlossenen Umschlag) oder</p><p>- mit Termin bei der Sachbearbeiterin oder dem Sachbearbeiter abgegeben werden</p><p>‍</p><p>Eine Wohngeld-Negativ-Bescheinigung kann durch die jeweilige Sachbearbeiterin bzw. den jeweiligen Sachbearbeiter ausgestellt werden (z.B. zur Vorlage bei der Bafög-Stelle)</p><p>‍</p><p>Voraussetzungen:</p><p>- Es muss sich um einen Wohnraum in Mainz handeln</p><p>- Einkommensgrenze für Wohngeldanträge:</p><p>Die nachstehende Übersicht zeigt die Grenzen des bereinigten monatlichen Haushaltseinkommens, bei deren Überschreitung unabhängig von der Miethöhe kein Wohngeldanspruch mehr besteht. Bei niedrigen Mieten können die Grenzen tiefer liegen.</p><p>1 Person &nbsp; - 1.010,00 Euro</p><p>2 Personen - 1.384,00 Euro</p><p>3 Personen - 1.673,00 Euro</p><p>4 Personen - 2.166,00 Euro</p><p>- Bei der Einkommensberechnung gibt es besondere Freibeträge, etwa für schwerbehinderte Personen. </p><p>- Auszubildende/Studenten haben als Alleinstehende dann keinen Anspruch auf Wohngeld, wenn ihnen grundsätzlich &nbsp;BAföG oder Berufsausbildungsbeihilfe nach dem Arbeitsförderungsrecht (Sozialgesetzbuch III) zusteht, es sei denn, die Leistungen wird ausschließlich als Darlehen gewährt. </p><p>- Bitte das Merkblatt mit ausführlichen Informationen für Studierende beachten (siehe unten)</p><p>- Alle weiteren Voraussetzungen werden im Einzelfall geprüft</p><p>‍</p><p>Unterlagen:</p><p>Antrag und alle beigefügten Vordrucke ausfüllen:</p><p> &nbsp;Vordrucke:</p><p> &nbsp;- Mietbescheinigung ausgefüllt vom Vermieter</p><p> &nbsp;- Verdienstbescheinigung ausgefüllt vom Arbeitgeber </p><p> &nbsp;- Erklärung zu sonstigen Einnahmen </p><p> &nbsp;- Erklärung zu ALG II </p><p>Zusätzlich:</p><p>- Mietquittungen der letzten drei Monate (z.B. Kontoauszüge)</p><p>- Einkommensnachweise aller Haushaltsmitglieder</p><p>- Rentenbescheid/ ALG I Bescheid/ BAföG- Bescheid</p><p>- ggf. Schulbescheinigung von Kindern</p><p>- Unter Umständen werden weitere Unterlagen benötigt, welche von der Sachbearbeiterin bzw. dem Sachbearbeiter gesondert angefordert &nbsp;werden.</p><p>‍</p><p>Rechtsgrundlagen:</p><p>- Wohngeldgesetz mit Verordnungen und Verwaltungsvorschriften</p><p>- SGB I</p><p>- SGB X u. a.</p>",
      "zielgruppe": "<p>Mieter, Wohnungseigentümer, Hauseigentümer</p>",
      "mehr-zu-diesem-thema": "<p>https://fm.rlp.de/de/themen/bauen-und-wohnen/wohngeld/</p>",
      "antwort-vorschau": "Wohngeld gibt es als Mietzuschuss für Mieterinnen und Mieter oder als Lastenzuschuss für Eigentümer einer Wohnung/ eines Hauses.",
      "slug": "wohngeld-beantragen",
      "zugehoriger-service-2": "581cad28b0231b7f5a75af0a",
      "updated-on": "2016-11-05T16:36:36.966Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:36:36.966Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0a94910be8fb11c085ec"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Unterstützung von Menschen die in folgenden Bereichen Hilfen benötigen:</p><p>- Körperpflege</p><p>- Haushalt</p><p>- Nahrungszubereitung und Aufnahme</p><p>- Hausnotruf</p><p>‍</p><p>Die Hilfen können durch Pflegedienste oder Privatpersonen erbracht werden.</p><p>‍</p><p>Die Hilfen werden gewährt in Form von:</p><p>- Sachleistungen (Bezahlung der Rechnung des Pflegedienstes bzw. der Privatperson)</p><p>- Geldleistung (Pflegegeld)</p>",
      "name": "Hilfe zur Pflege",
      "zustandige-stellen": "<p>Amt für soziale Leistungen</p>",
      "vorgehensweise-und-detail": "<p>Vor der ersten Antragstellung:</p><p>- Nehmen Sie bitte Kontakt mit einem der Pflegestützpunkte der Stadt Mainz oder mit dem Sozialdienst des Amtes für soziale Leistungen auf.</p><p>‍</p><p>Anspruchsberechtigt sind:</p><p>-Menschen die aufgrund einer Krankheit, Behinderung oder ähnlichen Einschränkungen die oben genannten Tätigkeiten nicht mehr selbst ausführen können</p><p>und</p><p>-Menschen, die sich nicht aus eigener wirtschaftlicher Kraft helfen können und nicht durch Leistungen Dritter unterstützt werden.</p><p>‍</p><p>Die&nbsp;Leistungen sind einkommens- und vermögensabhängig.</p>",
      "zielgruppe": "<p>Menschen, die Unterstützung benötigen</p>",
      "antwort-vorschau": "Unterstützung von Menschen die in folgenden Bereichen Hilfen benötigen: Körperpflege, Haushalt, Nahrungszubereitung und Aufnahme , Hausnotruf.",
      "slug": "hilfe-zur-pflege",
      "zugehoriger-service-2": "581cab1f5d7e0501760b95de",
      "updated-on": "2016-11-05T16:30:45.616Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:30:45.616Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e09359ee306e06532a692"
    },
    {
      "_archived": false,
      "_draft": false,
      "mehr-zu-diesem-thema": null,
      "antwort": "<p>Das Amt für soziale Leistungen ist zuständig für die Auszahlung der Grundsicherung im Alter und bei dauerhafter Erwerbsminderung nach dem SGB XII.</p><p>Ältere und dauerhaft voll erwerbsgeminderte Personen mit gewöhnlichem Aufenthalt im Inland erhalten auf Antrag Leistungen der Grundsicherung nach § 41 SGB XII, soweit sie bedürftig sind.</p>",
      "name": "Grundsicherung im Alter und bei Erwerbsminderung",
      "zustandige-stellen": "<p>Amt für soziale Leistungen</p>",
      "vorgehensweise-und-detail": "<p>Leistungsberechtigt sind Personen, die</p><p>• die Altersgrenze nach § 41 Abs. 2 SGB XII erreicht haben (gesetzliches Rentenalter) oder</p><p>• die das 18. Lebensjahr vollendet haben und unabhängig von der Arbeitsmarktlage voll erwerbsgemindert sind</p><p>‍</p><p>Weitere Voraussetzung ist, dass der Lebensunterhalt nicht (vollständig) aus eigenem Einkommen und Vermögen bestritten werden kann. Das Einkommen und Vermögen des nicht getrennt lebenden Ehegatten oder Lebenspartner sowie des Partners einer eheähnlichen Gemeinschaft wird, soweit es den Eigenbedarf übersteigt, ebenfalls berücksichtigt. Gegenüber Kindern und Eltern findet kein Unterhaltsrückgriff statt, wenn deren Jahreseinkommen unter 100.000,00 € liegt.</p><p>‍</p><p>Leistungen der Grundsicherung im Alter und bei Erwerbsminderung erhält nicht, wer in den letzten zehn Jahren die Bedürftigkeit vorsätzlich oder grob fahrlässig herbeigeführt hat.</p><p>‍</p><p>Die Höhe der Grundsicherung kann vorab nicht abgeschätzt werden, da eine individuelle Berechnung erfolgt.</p><p>‍</p><p>Grundsätzlich umfassen die Leistungen der Grundsicherung im Alter und bei Erwerbsminderung:</p><p>• den maßgebenden Regelsatz</p><p>• angemessene Aufwendungen für Unterkunft und Heizung</p><p>• Übernahme von Kranken- und Pflegeversicherungsbeiträgen</p><p>• Mehrbedarfe nach § 30 SGB XII</p><p>‍</p><p>Vor der Antragstellung:</p><p>Nehmen Sie bitte telefonisch Kontakt mit der zuständigen Sachbearbeiterin bzw. dem zuständigen Sachbearbeiter des Amtes für soziale Leistungen auf. Bei diesem Erstkontakt werden Ihnen auch die notwendigen Unterlagen genannt sowie ein Antrag zur Verfügung gestellt.</p><p>Persönliche Vorsprachen sind nur nach vorheriger Terminvereinbarung möglich.</p><p>‍</p><p>Zusätzliche Information</p><p>Grundsicherung im Alter und bei Erwerbsminderung und Wohngeld kann nicht nebeneinander bezogen werden. Je nach Sachverhalt wird die für die Antragstellerin bzw. den Antragsteller günstigere Leistung gewährt.</p>",
      "zielgruppe": "<p>Ältere und dauerhaft voll erwerbsgeminderte Personen mit gewöhnlichem Aufenthalt im Inland.</p>",
      "antwort-vorschau": "Das Amt für soziale Leistungen ist zuständig für die Auszahlung der Grundsicherung im Alter und bei dauerhafter Erwerbsminderung nach dem SGB XII.",
      "slug": "grundsicherung-im-alter-und-bei-erwerbsminderung",
      "zugehoriger-service-2": "581cab608a3443f84a3b5757",
      "updated-on": "2016-11-05T16:26:43.330Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:26:43.330Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0843b69ed76343e7b7a1"
    },
    {
      "_archived": false,
      "_draft": false,
      "mehr-zu-diesem-thema": null,
      "antwort": "<p>Sind die Eltern bei der Geburt des Kindes nicht miteinander verheiratet und wurde keine gemeinsame Sorgeerklärung abgegeben, so hat die Mutter das alleinige Sorgerecht.</p>",
      "name": "Sorgerechtsbescheinigung (Negativbescheinigung)",
      "zustandige-stellen": "<p>Amt für Jugend und Familie</p>",
      "vorgehensweise-und-detail": "<p>Für die Ausstellung einer Negativbescheinigung ist immer das Jugendamt zuständig,&nbsp; wo das Kind und die Mutter ihren gewöhnlichen Aufenthalt (Wohnort) haben. Das Jugendamt des Geburtsortes wendet sich ggf. im Rahmen der Amtshilfe an das Jugendamt des Wohnortes.<br></p><p>‍</p><p>Unterlagen:</p><p>- Gültiger Ausweis</p><p>- Geburtsurkunde (falls vorhanden)</p><p>‍</p><p>Gebühren:</p><p>Die Ausstellung der Bescheinigung ist gebührenfrei.</p>",
      "zielgruppe": "<p>nicht miteinander verheiratete Eltern</p>",
      "antwort-vorschau": "Sind die Eltern bei der Geburt des Kindes nicht miteinander verheiratet und wurde keine gemeinsame Sorgeerklärung abgegeben, so hat die Mutter das alleinige Sorgerecht.",
      "slug": "sorgerechtsbescheinigung-negativbescheinigung",
      "zugehoriger-service-2": "581df66fb69ed76343e787f7",
      "updated-on": "2016-11-05T16:22:04.520Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:22:04.520Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e072c9ee306e06532a1cc"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Betreuungsunterhalt kann gezahlt werden:</p><p>- in der Zeit bis zu 3 Jahre nach der Geburt</p><p>- für die nicht verheiratete Mutter eines Kindes; betreut der Vater das Kind, steht ihm der Anspruch zu</p><p>- zuständig für eine Beratung ist das Amt für Jugend und Familie</p>",
      "fristen": "<p>Betreuungsunterhalt kann gezahlt werden:</p><p>&gt; in der Zeit bis zu 3 Jahre nach der Geburt</p>",
      "name": "Betreuungsunterhalt",
      "zustandige-stellen": "<p>Amt für Jugend und Familie</p>",
      "zielgruppe": "<p>nicht verheiratete Mütter / Väter</p>",
      "antwort-vorschau": "Betreuungsunterhalt kannin der Zeit bis zu 3 Jahre nach der Geburt gezahlt werden.",
      "slug": "betreuungsunterhalt",
      "zugehoriger-service-2": "581df5e99ee306e065327e2a",
      "updated-on": "2016-11-05T16:17:07.314Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:17:07.314Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e0603910be8fb11c07f0c"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Steuergegenstand der Gewerbesteuer ist der Gewerbebetrieb mit seiner objektiven Ertragskraft.&nbsp;Unter \"Gewerbebetrieb\" ist ein gewerbliches Unternehmen im Sinne des Einkommensteuerrechts zu verstehen. Nicht der Gewerbesteuer unterliegt</p><p>- Urproduktion: z.B. Ausübung von Land- und Forstwirtschaft</p><p>- freie Berufe: z.B. Arzt, Rechtsanwalt, Steuerberater</p>",
      "name": "Gewerbesteuer",
      "zustandige-stellen": "<p>Amt für Finanzen, Beteiligungen und Sport</p>",
      "vorgehensweise-und-detail": "<p>Grundlage der Gewerbesteuer:</p><p>- Der Gewerbeertrag des Unternehmens bildet die Grundlage der Besteuerung </p><p>- Das ist der vom Steuerzahler erklärte Gewinn aus dem Gewerbebetrieb, der um bestimmte Beträge vermehrt und vermindert wird </p><p>‍</p><p>Höhe der Gewerbesteuer:</p><p>- Bei der Berechnung der Gewerbesteuer wird von einem Steuermessbetrag ausgegangen</p><p>- Für die Festsetzung des Messbetrages ist Ihr Finanzamt zuständig</p><p>- Dieser Messbetrag wird ermittelt durch die Multiplikation des Gewerbeertrages mit einer Steuermesszahl (in der Regel 3,5 %)</p><p>- Dabei ist für natürliche Personen und Personengesellschaften ein Freibetrag von 24.500 € zu berücksichtigen.</p><p>‍</p><p>Sollte die Berechnung des Messbetrages fehlerhaft sein, wenden Sie sich bitte an Ihr Finanzamt.</p><p>‍</p><p>Hat ein Unternehmen Betriebsstätten in mehreren Gemeinden, wird der Steuermessbescheid vom Finanzamt erteilt. &nbsp;Als Zerlegungsmaßstab werden grundsätzlich die Arbeitslöhne herangezogen.</p><p>‍</p><p>Die Gewerbesteuer wird von der Gemeinde aufgrund des Steuermessbetrages mit einem Hundertsatz (Hebesatz) festgesetzt und erhoben (Gewerbesteuer = Messbetrag x Hebesatz). Der Hebesatz der Stadt Mainz beträgt 440 Prozent. Er wird vom Stadtrat festgesetzt und ist seit vielen Jahren unverändert geblieben.</p><p>‍</p><p>Unterlagen:</p><p>- Bestätigung über Ausübung eines freien Berufes</p><p>- Lastschrifteinzugsverfahren:- Einzugsermächtigung per Post oder Fax an die Steuerverwaltung- vollständig ausgefüllt und unterschrieben (Vordruck)</p><p>‍</p><p>Hinweise:</p><p>- die Einzugsermächtigung hat so lange Gültigkeit, bis Sie von Ihnen schriftlich widerrufen wird</p><p>‍</p><p>- Sollte sich die Kontoverbindung ändern:</p><p>- schriftlich per Post oder Fax der Steuerverwaltung mitteilen,&nbsp;so kann mit der neuen Kontoverbindung weiterhin am Lastschrifteinzugsverfahren teilgenommen werden</p>",
      "zielgruppe": "<p>Gewerbliches Unternehmen im Sinne des Einkommensteuerrechts.</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Stadtkasse-SEPA-Lastschriftmandat.pdf</p>",
      "antwort-vorschau": "Steuergegenstand der Gewerbesteuer ist der Gewerbebetrieb mit seiner objektiven Ertragskraft. Unter \"Gewerbebetrieb\" ist ein gewerbliches Unternehmen im Sinne des Einkommensteuerrechts zu verstehen.",
      "slug": "gewerbesteuer",
      "zugehoriger-service-2": "581cae5e16e8e0ee061f828d",
      "updated-on": "2016-11-05T16:13:13.601Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:13:13.601Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e05194869c31f66b97528"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Folgende veranstaltete Vergnügungen unterliegen der Vergnügungssteuer:</p><p>- Tanzveranstaltungen jeder Art, soweit sie im Rahmen eines Berufes oder Gewerbes statt finden, </p><p>- der Betrieb von Bars sowie </p><p>- das Halten von Spiel- und Unterhaltungsgeräten</p><p>‍</p><p>Die Vergnügungssteuer ist eine örtliche Verbrauchs- und Aufwandssteuer;&nbsp; besteuert wird der Aufwand den der Teilnehmer an einer vergnügungssteuerpflichtigen Veranstaltung in seiner Einkommensverwendung betreibt und hierdurch eine wirtschaftliche Leistungsfähigkeit zum Ausdruck bringt.</p>",
      "fristen": "<p>Festsetzung und Bezahlung:</p><p>- Bei der Karten- sowie der Pauschsteuer wird die Steuer innerhalb von 14 Tagen nach Bescheiderteilung fällig</p><p>- Die Festsetzung der Vergnügungssteuer für eine Veranstaltungsreihe erfolgt für einen Kalendermonat</p><p>- Die Steuer ist hier am 1. des Folgemonats für den vorangegangenen Monat zu entrichten</p><p>- Für das Halten von Spiel- und Unterhaltungsgeräten sowie Musikboxen besteht der Steueranspruch für jeden Betriebsmonat (Kalendermonat). Auch hier ist die Steuer am 1. des Folgemonats zu entrichten.</p>",
      "name": "Vergnügungssteuer",
      "zustandige-stellen": "<p>Amt für Finanzen, Beteiligungen und Sport</p>",
      "vorgehensweise-und-detail": "<p>Anmeldung bei der Steuerverwaltung:</p><p>- schriftlich per Post oder Fax&nbsp;(Vordruck)</p><p>‍</p><p>Gebühren:</p><p>- Bei Veranstaltungen mit Eintritt:</p><p> &gt; beträgt der Steuersatz 20% des Eintrittspreises (Bruttoeintrittspreis)</p><p>- Bei Veranstaltungen ohne Eintritt: </p><p> &gt; wird die Steuer als Pauschsteuer nach der Raumgröße festgesetzt</p><p>- Für das Halten von Spiel- und Unterhaltungsgeräten und Musikboxen: </p><p> &gt; Unterhaltungsgeräte mit Gewinnmöglichkeit pro Gerät 60,00 Euro</p><p> &gt; Unterhaltungsgeräte ohne Gewinnmöglichkeit sowie Musikboxen pro Gerät 20,00 Euro</p><p>‍</p><p>Lastschrifteinzugsverfahren:</p><p>Die Stadtkasse bietet für die Zahlung der Hundesteuer das Lastschrifteinzugsverfahren an. Hierfür ist das Formular vollständig ausgefüllt und unterschrieben bei der Stadtkasse einzureichen (per Post oder Fax).</p><p>Die Einzugsermächtigung hat so lange Gültigkeit, bis sie schriftlich widerrufen wird.</p><p> Sollte sich die Kontoverbindung ändern, wird dies der Steuerverwaltung mitgeteilt.</p>",
      "zielgruppe": "<p>Steuerpflichtig ist </p><p>- der Unternehmer der Veranstaltung sowie </p><p>- der Halter von Spiel- und Unterhaltungsgeräten</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Vergnuegungssteuersatzung-Internet-Stand-01_03_2012.pdf</p><p>https://www.mainz.de/vv/Stadtkasse-SEPA-Lastschriftmandat.pdf</p><p>https://www.mainz.de/vv/vergnuegungssteuer_gewinnmoeglichkeit.pdf</p><p>https://www.mainz.de/vv/vergnuegungssteuer_unterhaltung.pdf</p><p>‍</p>",
      "antwort-vorschau": "Die Vergnügungssteuer ist eine örtliche Verbrauchs- und Aufwandssteuer.",
      "slug": "vergnugungssteuer",
      "zugehoriger-service-2": "581cae8a257cc18c5a3089d8",
      "updated-on": "2016-11-05T16:04:59.144Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T16:04:59.144Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e032b910be8fb11c077dd"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>‍Hundehalter ist:</p><p>- wer einen Hund in seinem Haushalt oder Betrieb aufgenommen hat</p><p>- aufgenommen ist ein Hund da, wo er untergebracht ist, betreut und versorgt wird (unabhängig davon, wer der Eigentümer ist)</p><p>- alle in einem Haushalt oder in einem Betrieb aufgenommenen Hunde gelten als gemeinsam gehalten</p><p>- halten mehrere Personen gemeinsam einen oder mehrere Hunde, so sind sie Gesamtschuldner</p><p>- wer einen Hund länger als 2 Monate in Pflege, Verwahrung oder auf Probe bzw. länger als drei Monate zum Anlernen hält</p>",
      "fristen": "<p>Anmeldung:</p><p>- binnen 14 Tagen nach der Anschaffung oder</p><p>- nach dem Zuzug</p><p>- die Steuerpflicht beginnt am 01. des auf die Anschaffung des Hundes folgenden Monats</p><p>- Bearbeitungszeit 1 - 3 Wochen</p><p>‍</p><p>Neugeborene Hunde:</p><p>- gelten mit Ablauf des dritten Monats nach der Geburt als angeschafft, also wird ab dann eine Anmeldung nötig</p><p>‍</p><p>Zugelaufene Hunde:</p><p>- gelten mit Ablauf von einem Monat nach dem Zulauf als angeschafft</p><p>‍</p><p>Abmeldung:</p><p>- Die Steuerpflicht endet mit Ablauf des Monats in dem der Hund abgeschafft wurde.</p><p>- Bearbeitungszeit 1 - 3 Wochen</p>",
      "name": "Hund anmelden (Hundesteuer)",
      "zustandige-stellen": "<p>Amt für Finanzen,\n &nbsp;Beteiligungen und Sport - Mainz</p>",
      "vorgehensweise-und-detail": "<p>Anmeldungen bei der Steuerverwaltung der Stadt Mainz:</p><p>- per Post oder Fax</p><p>- persönliche Vorsprache</p><p>‍</p><p>Bei Umzug innerhalb der Stadt Mainz ist der Steuerverwaltung lediglich die neue Anschrift mitzuteilen</p><p>- dies kann über das Online Formular erfolgen</p><p>- ausgefüllte Formulare zur Hundesteuer können auch im Bürgerservice abgegeben werden und werden an das Amt 20 weitergeleitet</p><p>‍</p><p>Hundesteuermarke:</p><p>- Hundehalter sind verpflichtet die Hundesteuermarke mit sich zu führen, sofern sie der Hund nicht am Halsband trägt</p><p>Voraussetzungen</p><p>‍</p><p>Unterlagen:</p><p>- ausgefülltes Formular</p><p>- Kopie des Impfausweises ( = EU-Heimtierausweis)</p><p>- Formular für die Einzugsermächtigung </p><p>- die Unterlagen, die im Einzelfall auf dem Formular genannt sind</p><p>‍</p><p>Gebühren:</p><p>- 1. Hund: 186,00 Euro</p><p>- 2. Hund: 216,00 Euro</p><p>- für jeden weiteren Hund: 216,00 Euro</p><p>- für jeden gefährlichen Hund: 600,00 Euro</p><p>Die Hundesteuer ist jährlich festgesetzt; die Zahlung erfolgt jedoch in vierteljährlichen Raten am 15.02., 15.05., 15.08. und 15.11.</p><p>‍</p><p>Ermäßigung bzw. Befreiung von der Hundesteuer in Ausnahmefällen:</p><p>- Für spezielle Sonderfälle sieht die Hundesteuersatzung geringere Sätze bzw. eine Befreiung vor</p><p>- In keinem Fall jedoch für gefährliche Hunde! Auch nicht, wenn der Besitzer Grundsicherung oder ALG II bezieht</p><p>- Weitere Infos siehe Merkblatt, bzw. Satzung</p><p>- bei ALG II Empfängern vermindert sich die Steuer um die Hälfte</p><p>‍</p><p>Lastschrifteinzugsverfahren:</p><p>- Die Stadtkasse bietet für die Zahlung der Hundesteuer das Lastschrifteinzugsverfahren an</p><p>- hierfür ist das Formular vollständig ausgefüllt und unterschrieben bei der Stadtkasse einzureichen (per Post oder Fax)</p><p>- die Einzugsermächtigung hat so lange Gültigkeit, bis sie schriftlich widerrufen wird</p><p>- Sollte sich die Kontoverbindung ändern, wird dies der Steuerverwaltung mitgeteilt</p><p>‍</p><p>Welche Hunde fallen unter \"gefährliche Hunde\"</p><p>1) Alle Hunde folgender Rassen: (und von ihnen abstammende Hunde)</p><p>&gt; American Staffordshire Terrier</p><p>&gt; Staffordshire Bullterrier</p><p>&gt; Pit Bull Terrier</p><p>2) Hunde, die von folgenden Rassen abstammen</p><p>- werden als gefährlich eingestuft so lange nicht das Gegenteil nachgewiesen wird &nbsp;(Nachweis erfolgt durch ein tierärztliches Gutachten)</p><p>&gt; Bullmastiff</p><p>&gt; Bull Terrier</p><p>&gt; Dogo Argentino</p><p>&gt; Fila Brasileiro</p><p>&gt; Mastiff</p><p>&gt; Mastino Napoletano</p><p>&gt; Tosa Inu</p><p>3) ALLE Hunde, (theoretisch auch Dackel)</p><p>&gt; die sich bereits als bissig erwiesen haben</p><p>&gt; die durch ihr Verhalten gezeigt haben, dass sie Wild oder Vieh hetzen oder reißen</p><p>&gt; die in aggressiver oder Gefahr drohender Weise Menschen angesprungen haben</p><p>&gt; die über das natürliche Maß hinausgehende Kampfbereitschaft, Angriffslust, Schärfe </p><p>oder eine andere vergleichbare Eigenschaft entwickelt haben</p>",
      "zielgruppe": "<p>Hundehalter</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/vv/Hundesteuersatzung-Internet-Stand-01_03_2012.pdf</p><p>https://www.mainz.de/vv/Stadtkasse-SEPA-Lastschriftmandat.pdf</p><p>https://www.mainz.de/vv/Hundesteuer-Anmeldung.pdf</p><p>https://www.mainz.de/vv/Hundesteuer-Abmeldung.pdf</p><p>https://www.mainz.de/vv/Hundesteuer-Adressaenderung_bei_Umzug_in_Mainz.pdf</p>",
      "antwort-vorschau": "Für das Halten von Hunden innerhalb der Stadt Mainz entrichtet der Hundehalter eine Steuer.",
      "slug": "hund-anmelden-hundesteuer",
      "zugehoriger-service-2": "581ca8208a3443f84a3b4476",
      "updated-on": "2016-11-05T15:54:30.607Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T15:54:30.607Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581e00b64869c31f66b970d8"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Eingetragene Mainzer Sportvereine können Zuschüsse gemäß den städtischen Sportförderrichtlinien beantragen, zum Beispiel Gerätezuschüsse (Sportgeräte, Wertgrenze ab 500.-€), Zuschüsse zu vereinseigenen Baumaßnahmen, Zuschüsse für die Anmietung von Sport-/Übungsflächen, Jubiläumszuschüsse. Die Zuschüsse werden auf Antrag (formlos) gewährt. Dem Antrag sind entsprechende Kostenvoranschläge beizufügen. Gegen Vorlage entsprechender Zahlungsbelege werden Zuschüsse auf das Vereinskonto gezahlt. Im Falle von Zuschüssen für vereinseigene Baumaßnahmen entscheidet der Sportausschuss.</p>",
      "fristen": "<p>Bearbeitungszeit:</p><p>Zuschussanträge zu vereinseigenen Baumaßnahmen müssen vor Beginn der Bau-/Sanierungsmaßnahmen gestellt werden. Bei positiver Bescheidung werden sie im Dezember des Jahres, in dem diese Maßnahmen stattfanden, gezahlt. Die Entscheidung darüber trifft der Sportausschuss. Die Jugendförderung und Vereinszuschüsse für eigene Sportstätten werden einmal jährlich im Dezember ausgezahlt. Zuschüsse unter 1.000 Euro können zeitnah gezahlt werden.</p>",
      "name": "Sportförderung beantragen",
      "zustandige-stellen": "<p>Amt für Finanzen, Beteiligungen und Sport - Mainz</p>",
      "vorgehensweise-und-detail": "<p>Zahlungsart:&nbsp;Die Zuschusszahlung erfolgt per Überweisung.</p><p>Rechtsgrundlagen:&nbsp;Sportfördergesetz von Rheinland-Pfalz, Sportförderrichtlinien der Stadt Mainz</p>",
      "zielgruppe": "<p>Eingetragene Mainzer Sportvereine</p>",
      "mehr-zu-diesem-thema": "<p>https://www.mainz.de/freizeit-und-sport/sport.php</p>",
      "antwort-vorschau": "Eingetragene Mainzer Sportvereine können Zuschüsse gemäß den städtischen Sportförderrichtlinien beantragen, die Zuschüsse werden auf Antrag (formlos) gewährt.",
      "slug": "sportforderung-beantragen",
      "zugehoriger-service-2": "581ca85aac3e3c9b2619b991",
      "updated-on": "2016-11-05T15:42:25.398Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-05T15:42:25.398Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-05T17:58:31.507Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581dfde14869c31f66b96c9e"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Die elterliche Sorge ist die Gesamtheit der dem Vater und der Mutter übertragenen Rechte und Pflichten in Bezug auf die Person und das Vermögen ihres minderjährigen Kindes, um es im Hinblick auf seine Sicherheit, seine Gesundheit und seine sittliche Entwicklung zu schützen. Sie ist das, was sich als logische Folge aus dem Sorge-, Aufsichts- und Erziehungsrecht und den entsprechenden Pflichten ergibt.</p><p>Diese gemeinsame elterliche Sorge für Kinder stellt kein Problem dar, wenn die Eltern verheiratet sind. Während der Ehe üben die Eltern die elterliche Sorge gemeinsam aus.</p><p>Wenn die Eltern geschieden sind oder offiziell getrennt leben, wird die elterliche Sorge grundsätzlich von demjenigen Elternteil ausgeübt, dem das Gericht nach einer Scheidung oder offiziellen Trennung das Sorgerecht zugesprochen hat, wobei das Besuchs- und Aufsichtsrecht des anderen Elternteils hiervon unberührt bleibt.</p><p>Somit stellt sich die Frage, ob nicht verheiratete bzw. geschiedene Eltern auch einen Anspruch auf eine gemeinsame elterliche Sorge (Sorgerecht für das Kind) geltend machen können.</p><p>Die zu unternehmenden Schritte und Modalitäten für die Zuerkennung der gemeinsamen elterlichen Sorge können je nach gewähltem Scheidungsverfahren sowie Zeitpunkt der Antragstellung unterschiedlich sein.</p>",
      "name": "Nach einer Scheidung oder Trennung der Eltern das gemeinsame Sorgerecht für ein Kind beantragen",
      "zustandige-stellen": "<p>Bezirksgerichte</p>",
      "vorgehensweise-und-detail": "<h5>Nicht verheiratete Eltern</h5><p>Bei einem Kind, dessen Eltern nicht verheiratet sind, wird die elterliche Sorge von demjenigen Elternteil ausgeübt, der es freiwillig anerkannt hat. Wenn es von beiden anerkannt wurde, wird sie nach dem Gesetz von der Mutter ausgeübt. Diese Regelung wurde allerdings vom Verfassungsgericht für verfassungswidrig erklärt, da sie der Gleichheit der Bürger vor dem Gesetz widerspricht. Dies bedeutet aber nicht zwangsläufig, dass die elterliche Sorge gemeinsam ausgeübt wird, da der Richter im Interesse des Kindeswohls entscheiden kann, das Sorgerecht nur einem der beiden Elternteile zuzuerkennen.</p><p>Anders ausgedrückt: Wenn die Eltern das gemeinsame Kind beide anerkannt haben, kann der Vater der alleinigen Ausübung der elterlichen Sorge durch die Mutter widersprechen, es sei denn, der Richter entscheidet, dass die elterliche Sorge im Interesse des Kindeswohls nur von der Mutter ausgeübt wird.</p><p>Auf jeden Fall kann die elterliche Sorge gemeinsam von nicht verheirateten Eltern ausgeübt werden, wenn sie dies gemeinsam beim Vormundschaftsrichter beantragen.</p><p>Dieser Antrag ist als Gesuch in freier Schriftform beim Vormundschaftsrichter einzureichen. Einen Anwalt am Gerichtshof hinzuzuziehen, ist nicht erforderlich. Die Verfahrensfristen sind zeitnah gestaltet und die anfallenden Kosten gering.</p><p>‍</p><h5>In Scheidung lebende Eltern</h5><p>Derzeit zögert die Rechtsprechung, in Scheidung lebenden Eltern ein gemeinsames Sorgerecht einzuräumen, womit sie sehr eng den Gesetzestexten folgt, die als einem gemeinsamen Sorgerecht zuwiderlaufend interpretiert werden können.</p><p>Somit kann ein gemeinsames Sorgerecht im Rahmen einer Scheidungsklage im Prinzip nicht bewilligt werden, und zwar weder durch einstweilige Verfügung (vorläufig) noch durch eine Entscheidung in der Hauptsache (endgültiger Beschluss).</p><p>‍</p><h5>Eltern, die sich in beiderseitigem Einvernehmen scheiden lassen wollen</h5><p>Auch wenn dies in keinem Gesetz vorgesehen ist, steht der Vorsitzende des Bezirksgerichts, der über Scheidungsanträge in beiderseitigem Einvernehmen erkennt, offensichtlich einem gemeinsamen Sorgerecht nicht ablehnend gegenüber, wenn ein solches von den Eltern im Rahmen der Scheidungsvereinbarung in beiderseitigem Einvernehmen ausdrücklich vorgesehen wurde.</p><p>Juristisch gesprochen handelt es sich vielmehr um eine Tolerierung als um eine strikte Anwendung der Gesetzestexte.</p><p>Wie dem auch sei, ist das gemeinsame Sorgerecht (die gemeinsame elterliche Sorge) im Rahmen einer Scheidung in beiderseitigem Einvernehmen vorstellbar.</p><p>‍</p><h5>Geschiedene Eltern</h5><p>Das Vormundschaftsgericht kann nach einer Scheidung das Sorgerecht jederzeit im Interesse des höchstmöglichen Kindeswohls festlegen, ändern oder ergänzen.</p><p>Die Rechtsprechung des Vormundschaftsgerichts geht bisher offensichtlich immer noch in Richtung einer Ablehnung eines gemeinsamen Sorgerechts (einer gemeinsamen elterlichen Sorge), und dies auch dann, wenn beide geschiedenen Elternteile einem solchen zugestimmt haben, und trotz der Empfehlungen der Staatsanwaltschaft, die das Konzept der gemeinsamen elterlichen Sorge im Falle des Einvernehmens der geschiedenen Eltern oftmals auch nicht mehr ablehnt.</p><p>In diesem Zusammenhang hat das Verfassungsgericht vor kurzem entschieden, dass die Artikel des luxemburgischen bürgerlichen Gesetzbuchs (Code civil), die die Ausübung der elterlichen Sorge allein dem Elternteil zuerkennen, dem das Sorgerecht für das Kind zugesprochen wurde, verfassungswidrig sind und gegen das Prinzip der Gleichheit vor dem Gesetz verstoßen, da das Gesetz gleichzeitig eine gemeinsame elterliche Sorge für nicht verheiratete Eltern, die ihr Kind anerkannt haben, vorsieht. Folglich könnte der Elternteil, der das Sorgerecht für das gemeinsame Kind nicht erhalten hat, rechtsgültig fordern, dass die elterliche Sorge von den Eltern gemeinsam ausgeübt wird, wenn dies im Interesse des Kindeswohls liegt.</p>",
      "zielgruppe": "<p>- Nicht verheiratete Eltern, die ein gemeinsames Kind haben;</p><p>- in Scheidung lebende Eltern;</p><p>- Eltern, die sich in beiderseitigem Einvernehmen scheiden lassen wollen;</p><p>- geschiedene Eltern.</p>",
      "mehr-zu-diesem-thema": "<h5>Verwandte Verwaltungsvorgänge</h5><p>Das Sorgerecht/Besuchsrecht für ein Kind nach offizieller Trennung oder Scheidung beantragen</p><p>‍</p><h5>Zusätzliche Informationen</h5><p>Unterhaltszahlungen auf der Internetseite Your Europe</p><p>‍</p><h5>Gesetzliche Grundlagen (nur in französischer Sprache)</h5><p>Sehen Sie sich auf legilux.lu die Verweise auf (in) diese(n) gesetzlichen Grundlagen sowie ihre chronologische Entwicklung an</p><p>Code civil - Livre I, Titre VI - Chapitre II</p><p>Du divorce pour cause déterminée</p><p>Code civil – Livre I, Titre IX</p><p>De l'autorité parentale</p>",
      "antwort-vorschau": "Die elterliche Sorge ist die Gesamtheit der dem Vater und der Mutter übertragenen Rechte und Pflichten in Bezug auf die Person und das Vermögen ihres minderjährigen Kindes, um es im Hinblick auf seine Sicherheit, seine Gesundheit und seine sittliche Entwicklung zu schützen. Sie ist das, was sich als logische Folge aus dem Sorge-, Aufsichts- und Erziehungsrecht und den entsprechenden Pflichten ergibt.",
      "slug": "nach-einer-scheidung-oder-trennung-der-eltern-das-gemeinsame-sorgerecht-fur-ein-kind-beantragen",
      "updated-on": "2016-11-01T21:58:31.060Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-01T21:37:11.831Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-01T22:20:33.229Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "zugehoriger-service-2": "57fa1c47fb1c83e918358bc7",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "58190b0744c96c8167caeac2"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>In Sachen Anerkennung einer Ehe gilt grundsätzlich, dass eine nach dem Recht des Staates, in dem die Trauung vollzogen wurde, rechtskräftig geschlossene Ehe oder eine anschließend dort rechtskräftig gewordene Ehe in jedem anderen Staat anerkannt werden muss.</p><p>Ein Ehepaar, das im Ausland geheiratet hat, hat aus vielerlei Gründen ein Interesse daran, dass diese Ehe in Deutschland&nbsp;anerkannt wird, wenn es beschließt, sich dort niederzulassen. Dies gilt insbesondere in steuerlicher Hinsicht, im Hinblick auf die Sozialversicherung sowie auf die Kindschaftsverhältnisse.</p><p>Die deutsche Behörden haben nicht von vornherein Kenntnis über eine im Ausland geschlossene Ehe, so dass die betroffenen Personen selbst tätig werden müssen, damit die Ehe in Deutschland offiziell anerkannt wird.&nbsp;</p>",
      "name": "Eine im Ausland geschlossene Ehe anerkennen lassen",
      "zustandige-stellen": "<p>Gemeindeverwaltung</p>",
      "vorgehensweise-und-detail": "<h5>Antrag auf Anerkennung einer im Ausland geschlossenen Ehe</h5><p>Um ihre im Ausland geschlossene Ehe anerkennen zu lassen, müssen die beiden Eheleute vor dem Standesbeamten der Gemeinde ihres gemeinsamen Wohnsitzes erscheinen. Damit die Anerkennung erfolgen kann, sind zwingend folgende Unterlagen beizubringen:</p><p>gültiger Personalausweis für luxemburgische Staatsangehörige;</p><p>gültiger Reisepass für ausländische Staatsangehörige;</p><p>ordnungsgemäß nach den Regeln des Landes, in dem die Ehe geschlossen wurde, beglaubigte Heiratsurkunde.</p><p>Der Wohnsitz der Personen wird vom Standesbeamten bei der Zusammenstellung der Akte überprüft.</p><p>Jede im Ausland ausgestellte Personenstandsurkunde (wie z.B. die Heiratsurkunde) von Luxemburgern und Ausländern hat in Luxemburg Gültigkeit, wenn sie entsprechend der im jeweiligen Land gebräuchlichen Form abgefasst wurde. Von den zuständigen Behörden im Ausland ausgestellte und Luxemburger betreffende Heiratsurkunden können in die Personenstandsregister ihres Wohnsitzes eingetragen werden.</p><p>Sobald der Nachweis der Eheschließung durch Vorlage der Heiratsurkunde (ausgestellt gemäß den Formvorschriften nach dem am Ort der Trauung geltenden Recht) erbracht wurde, gilt die Ehe als vor den luxemburgischen Behörden geschlossen, wobei das luxemburgische Recht die im Ausland ausgestellten Personenstandsurkunden als gültig anerkennt.</p><h5>‍Gründe für eine Ablehnung des Anerkennungsantrags</h5><p>Der Standesbeamte kann die Anerkennung der Gültigkeit einer Ehe ablehnen, wenn einer der Eheleute nach luxemburgischen Recht zum Zeitpunkt dieser Eheschließung:</p><p>bereits verheiratet war, oder</p><p>in einem Verwandtschaftsgrad in gerader Linie mit dem jeweils anderen Ehepartner stand oder sein Bruder oder seine Schwester durch Blutsverwandtschaft oder Adoption war, oder</p><p>nicht das erforderliche Mindestalter zum Heiraten hatte und ihm keine Heiratserlaubnis erteilt wurde, oder</p><p>geistig nicht in der Lage war, eine rechtsgültige Einwilligung abzugeben, oder</p><p>der Ehe nicht freiwillig zugestimmt hat.</p><p>Die Anerkennung kann auch abgelehnt werden, wenn diese Eheschließung offensichtlich mit der öffentlichen Ordnung im Großherzogtum Luxemburg unvereinbar ist (Polygamie usw.).</p>",
      "zielgruppe": "<p>Folgende Personen können betroffen sein:</p><p>Gebietsansässige, die einen Drittstaatsangehörigen in diesem Drittland oder in einem anderen ausländischen Staat (EU-Mitgliedstaat oder nicht) geheiratet haben, der auf luxemburgischem Staatsgebiet rechtmäßig wohnen möchte;</p><p>Drittstaatsangehörige (EU-Mitgliedstaat oder nicht), die im Ausland (in der EU oder einem anderen Land) eine Ehe eingegangen sind und rechtmäßig auf luxemburgischem Staatsgebiet wohnen möchten.</p>",
      "mehr-zu-diesem-thema": "<h5>Zusätzliche Informationen</h5><p>Regelungen bezüglich der Ehe auf \"Your Europe\"</p><p>Das Recht für Paare in Europa</p><h5>Gesetzliche Grundlagen</h5><p>Sehen Sie sich auf legilux.lu die Verweise auf (in) diese(n) gesetzlichen Grundlagen sowie ihre chronologische Entwicklung an</p><p>Code civil – Livre I, Titre II</p><p>Des actes de l’état civil </p><p>Loi du 20 décembre 1990</p><p>portant approbation de la Convention sur la célébration et la reconnaissance de la validité des mariages, signée à La Haye, le 14 mars 1978</p>",
      "antwort-vorschau": "In Sachen Anerkennung einer Ehe gilt grundsätzlich, dass eine nach dem Recht des Staates, in dem die Trauung vollzogen wurde, rechtskräftig geschlossene Ehe oder eine anschließend dort rechtskräftig gewordene Ehe in jedem anderen Staat anerkannt werden muss. Ein Ehepaar, das im Ausland geheiratet hat, hat aus vielerlei Gründen ein Interesse daran, dass diese Ehe in Deutschland anerkannt wird, wenn es beschließt, sich dort niederzulassen. Dies gilt insbesondere in steuerlicher Hinsicht, im Hinblick auf die Sozialversicherung sowie auf die Kindschaftsverhältnisse.",
      "slug": "eine-im-ausland-geschlossene-ehe-anerkennen-lassen",
      "updated-on": "2016-11-01T21:58:39.147Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-01T21:34:45.099Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-01T22:20:33.229Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "zugehoriger-service-2": "57fa1c1745bf29a4636a63c2",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "58190a75121bc0d10cf64dd4"
    },
    {
      "_archived": false,
      "_draft": false,
      "antwort": "<p>Um in Deutschland standesamtlich heiraten zu können, sind im Vorfeld bestimmte Behördengänge zu erledigen und verschiedene Unterlagen beizubringen (die je nach Staatsangehörigkeit der zukünftigen Ehepartner variieren können).</p><p>Die kirchliche Trauung darf erst nach der standesamtlichen Hochzeit stattfinden. Demnach ist eine rein kirchliche Trauung, d.h. ohne vorhergehende standesamtliche Eheschließung, verboten.</p>",
      "fristen": "<p>Mit den Vorbereitungen für die standesamtliche Trauung sollte spätestens mit folgendem zeitlichen Vorlauf begonnen werden (als Anhaltspunkt):</p><p>2 Monate vor dem Hochzeitstermin bei Gebietsansässigen mit luxemburgischer Staatsangehörigkeit;</p><p>3 Monate vor dem Hochzeitstermin bei Gebietsansässigen nicht luxemburgischer Herkunft.</p><p>Die Ehe darf nur in einer Gemeinde geschlossen werden, in der einer der zukünftigen Ehepartner seinen gesetzlichen Wohnsitz hat.</p>",
      "name": "Standesamtlich heiraten",
      "zustandige-stellen": "<p>Gemeindeverwaltung</p><p>Botschaft und Konsulat</p>",
      "vorgehensweise-und-detail": "<h5>Im Vorfeld zu erledigende Behördengänge zur Zusammenstellung der für die Eheschließung notwendigen Papiere</h5><p>Folgende im Vorfeld zu erledigende Behördengänge sind einzuplanen:</p><p>Einer der beiden zukünftigen Ehepartner muss beim Standesbeamten der Gemeinde vorstellig werden, in der einer von ihnen seinen gesetzlichen Wohnsitz hat (wahlweise), um die vorbereitenden Formalitäten für die Eheschließung zu erledigen (er muss seinen Personalausweis/Reisepass und den seines zukünftigen Ehepartners mitbringen);</p><p>der Standesbeamte übergibt ihm die entsprechenden Formulare für die zu erledigenden Behördengänge und gibt an, welche Unterlagen beizubringen sind. Die zur Eheschließung erforderlichen Unterlagen (siehe hierzu Etappe 4) müssen zwingend auf Französisch, Deutsch oder Englisch abgefasst sein. Ist dies nicht der Fall, müssen die zukünftigen Ehepartner:</p><p>entweder eine nationale Urkunde besorgen, die mit einer Unterschriftsbeglaubigung oder Apostille (Haager Übereinkommen) versehen und von einem vereidigten Übersetzer in eine dieser 3 Sprachen übersetzt ist (eine Liste der vereidigten Übersetzer kann beim Justizministerium angefordert werden);</p><p>oder eine internationale Urkunde (gemäß Anhang des CIEC-Übereinkommens Nr. 16) beantragen.</p><p>Die erforderlichen Unterlagen müssen dem Standesamt spätestens 1 Monat vor dem Hochzeitstermin vorgelegt werden.</p><p>‍</p><h5>Eheschließung</h5><p>Aufgrund der im Vorfeld zu erledigenden Formalitäten liegt es im Interesse der künftigen Ehepartner, mindestens 2 bis 3 Monate vor dem geplanten Hochzeitstermin Kontakt zum Standesamt aufzunehmen.</p><p>In Luxemburg muss vor der Eheschließung ein Aufgebot bestellt werden, das 10 Tage lang in der Wohnsitzgemeinde der künftigen Ehepartner aushängt. Dieses Aufgebot erfolgt, sobald der Gemeinde, in der die Ehe geschlossen werden soll, die erforderlichen Unterlagen vorgelegt wurden.</p><p>Bei Personen, die vor weniger als 6 Monaten in eine andere Wohnsitzgemeinde umgezogen sind, muss das Aufgebot auch in der vorherigen Wohnsitzgemeinde veröffentlicht werden.</p><p>Anschließend muss die Ehe innerhalb von 12 Monaten nach Ablauf der Aufgebotsfrist geschlossen werden. Andernfalls muss ein neues Aufgebot bestellt werden.</p><p>Der Hochzeitstermin (Tag und Uhrzeit) wird bei Vorlage aller für das Aufgebot notwendigen Unterlagen festgelegt.</p><p>Grundsätzlich können Ehen an jedem Tag (Werktag) der Woche geschlossen werden. Die Trauung muss zwingend im Rathaus stattfinden.</p><p>Ist dies aus schwerwiegenden Gründen nicht möglich, kann der für den Ort der Eheschließung zuständige Staatsanwalt den Standesbeamten auffordern, sich zur Wohnung oder zum Wohnsitz eines der Ehepartner zu begeben, um die Eheschließung vorzunehmen.</p>",
      "zielgruppe": "<p>Sowohl verschiedengeschlechtliche als auch gleichgeschlechtliche Paare können standesamtlich heiraten.</p><p>Die Vorbereitungen für die standesamtliche Hochzeit muss jeder treffen, der in Deutschland&nbsp;heiraten möchte, unabhängig von seiner Staatsangehörigkeit.</p><p>Um in Deutschland heiraten zu können, müssen die zukünftigen Ehepartner mindestens 18 Jahre alt sein und einer von ihnen muss seinen offiziellen Wohnsitz in Luxemburg haben.</p><p>Auch für Minderjährige besteht die Möglichkeit zu heiraten. Hierzu ist jedoch eine Erlaubnis des Vormundschaftsrichters erforderlich.</p>",
      "mehr-zu-diesem-thema": "<h5>Zusätzliche Informationen</h5><p>Contrat de mariage sur le site de la Chambre des notaires</p><p>Regelungen bezüglich der Ehe auf \"Your Europe\"</p><p>Site de l'Association luxembourgeoise des traducteurs et interprètes (ALTI)</p><h5>Gesetzliche Grundlagen</h5><p>Sehen Sie sich auf legilux.lu die Verweise auf (in) diese(n) gesetzlichen Grundlagen sowie ihre chronologische Entwicklung an</p><p>Code civil – Livre I, Titre V</p>",
      "antwort-vorschau": "Um in Deutschland standesamtlich heiraten zu können, sind im Vorfeld bestimmte Behördengänge zu erledigen und verschiedene Unterlagen beizubringen (die je nach Staatsangehörigkeit der zukünftigen Ehepartner variieren können). Die kirchliche Trauung darf erst nach der standesamtlichen Hochzeit stattfinden. Demnach ist eine rein kirchliche Trauung, d.h. ohne vorhergehende standesamtliche Eheschließung, verboten.",
      "slug": "standesamtlich-heiraten",
      "updated-on": "2016-11-01T21:58:48.671Z",
      "updated-by": "Person_57f9ed0680f06b4c0306ce82",
      "created-on": "2016-11-01T21:31:34.647Z",
      "created-by": "Person_57f9ed0680f06b4c0306ce82",
      "published-on": "2016-11-01T22:20:33.229Z",
      "published-by": "Person_57f9ed0680f06b4c0306ce82",
      "zugehoriger-service-2": "57fa1c1745bf29a4636a63c2",
      "_cid": "5819084844c96c8167cadfd0",
      "_id": "581909b64637d3c60cea5bd4"
    }
  ],
  "count": 26,
  "limit": 100,
  "offset": 0,
  "total": 26
}