--<DROP SCHEMA IF EXISTS DATENBASIS; -->
--<CREATE SCHEMA IF NOT EXISTS DATENBASIS; -->
--<SET SCHEMA DATENBASIS;-->

DROP TABLE IF EXISTS BERATUNGSTHEMEN_GEBIETE;
CREATE TABLE IF NOT EXISTS BERATUNGSTHEMEN_GEBIETE
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	BESCHREIBUNG VARCHAR(2000) NOT NULL,
	IMAGE_HEADER VARCHAR(255) NOT NULL,
	IMAGE_PROFILE VARCHAR(255) NOT NULL,
	CREATION_BY VARCHAR(255),
	CREATION_ON TIMESTAMP,
	LASTUPDATE_BY VARCHAR(255),
	LASTUPDATE_ON TIMESTAMP
);




DROP TABLE IF EXISTS BERATER;
CREATE TABLE IF NOT EXISTS BERATER
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TYP VARCHAR(255) check (TYP in ('SACHBEARBEITER', 'SUPER_USER', 'ADMIN')),
	ANREDE VARCHAR(4) check (ANREDE in ('Herr','Frau')),
	NAME VARCHAR(255) NOT NULL,
	VORNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	TELEFON VARCHAR(255) UNIQUE NOT NULL,
	ANWESENHEIT_MONTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	ANWESENHEIT_MONTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	ANWESENHEIT_MONTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	ANWESENHEIT_MONTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	ANWESENHEIT_DIENSTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	ANWESENHEIT_DIENSTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	ANWESENHEIT_DIENSTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	ANWESENHEIT_DIENSTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	ANWESENHEIT_MITTWOCH_MORGEN_VON TIME DEFAULT '08:00:00',
	ANWESENHEIT_MITTWOCH_MORGEN_BIS TIME DEFAULT '11:30:00',
	ANWESENHEIT_MITTWOCH_MITTAG_VON TIME DEFAULT '12:30:00',
	ANWESENHEIT_MITTWOCH_MITTAG_BIS TIME DEFAULT '17:00:00',
	ANWESENHEIT_DONNERSTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	ANWESENHEIT_DONNERSTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	ANWESENHEIT_DONNERSTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	ANWESENHEIT_DONNERSTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	ANWESENHEIT_FREITAG_MORGEN_VON TIME DEFAULT '08:00:00',
	ANWESENHEIT_FREITAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	ANWESENHEIT_FREITAG_MITTAG_VON TIME DEFAULT '12:30:00',
	ANWESENHEIT_FREITAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	BERATUNGSTHEMEN VARCHAR(255) NOT NULL,
	PROFILBILD VARCHAR(255) NOT NULL,
	AMTS_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS LOGGING;
CREATE TABLE IF NOT EXISTS LOGGING
(
	REQUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	REQUEST_UUID UUID,
	REQUEST_CALLERNAME VARCHAR(255) NOT NULL,
	REQUEST_TIMESTAMP TIMESTAMP,
	REQUEST_TYPE VARCHAR(255) NOT NULL,
	REQUEST_DATAOBJEKT VARCHAR(255) NOT NULL,
	REQUEST_FULLURL VARCHAR(255) NOT NULL,
	REQUEST_PAYLOAD CLOB,
	JOB_LOG CLOB,
	RESPONSE_STATUS VARCHAR(255) NOT NULL,
	RESPONSE_PAYLOAD CLOB,
	REPONSE_TIMESTAMP TIMESTAMP
);

DROP TABLE IF EXISTS BERATUNGSTHEMEN_SERVICES;
CREATE TABLE IF NOT EXISTS BERATUNGSTHEMEN_SERVICES
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	TAGS VARCHAR(2000) NOT NULL,
	BERATUNGSTHEMA_GEBIET_ID BIGINT NOT NULL,
	AMTSART_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS AMTSARTEN;
CREATE TABLE IF NOT EXISTS AMTSARTEN
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	OFFIZIELLER_NAME VARCHAR(2000) NOT NULL,
	LOGO VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS AEMTER;
CREATE TABLE IF NOT EXISTS AEMTER
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	AMTSART_ID BIGINT NOT NULL,
	ADRESSE VARCHAR(255) NOT NULL,
	PLZ BIGINT NOT NULL,
	ORT VARCHAR(255) NOT NULL,
	MAIL VARCHAR(255) NOT NULL,
	TELEFON VARCHAR(255) NOT NULL,
	URL VARCHAR(255) NOT NULL,
	PLZ_GEBIET_VON BIGINT NOT NULL,
	PLZ_GEBIET_BIS BIGINT NOT NULL,
	OEFFNUNGSZEITEN_MONTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	OEFFNUNGSZEITEN_MONTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	OEFFNUNGSZEITEN_MONTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	OEFFNUNGSZEITEN_MONTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	OEFFNUNGSZEITEN_DIENSTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	OEFFNUNGSZEITEN_DIENSTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	OEFFNUNGSZEITEN_DIENSTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	OEFFNUNGSZEITENDIENSTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	OEFFNUNGSZEITEN_MITTWOCH_MORGEN_VON TIME DEFAULT '08:00:00',
	OEFFNUNGSZEITEN_MITTWOCH_MORGEN_BIS TIME DEFAULT '11:30:00',
	OEFFNUNGSZEITEN_MITTWOCH_MITTAG_VON TIME DEFAULT '12:30:00',
	OEFFNUNGSZEITEN_MITTWOCH_MITTAG_BIS TIME DEFAULT '17:00:00',
	OEFFNUNGSZEITEN_DONNERSTAG_MORGEN_VON TIME DEFAULT '08:00:00',
	OEFFNUNGSZEITEN_DONNERSTAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	OEFFNUNGSZEITEN_DONNERSTAG_MITTAG_VON TIME DEFAULT '12:30:00',
	OEFFNUNGSZEITEN_DONNERSTAG_MITTAG_BIS TIME DEFAULT '17:00:00',
	OEFFNUNGSZEITEN_FREITAG_MORGEN_VON TIME DEFAULT '08:00:00',
	OEFFNUNGSZEITEN_FREITAG_MORGEN_BIS TIME DEFAULT '11:30:00',
	OEFFNUNGSZEITEN_FREITAG_MITTAG_VON TIME DEFAULT '12:30:00',
	OEFFNUNGSZEITEN_FREITAG_MITTAG_BIS TIME DEFAULT '17:00:00'
);

DROP TABLE IF EXISTS DOKUMENTENTYPEN;
CREATE TABLE IF NOT EXISTS DOKUMENTENTYPEN
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	ENDUNG VARCHAR(3) UNIQUE NOT NULL,
	LOGO VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS DOKUMENTE;
CREATE TABLE IF NOT EXISTS DOKUMENTE
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	PFAD VARCHAR(255) UNIQUE NOT NULL,
	ZUGEHOERIGE_FRAGEN BIGINT NOT NULL,
	DOKUMENTENTYP BIGINT NOT NULL
);

DROP TABLE IF EXISTS INFORMATIONEN;
CREATE TABLE IF NOT EXISTS INFORMATIONEN
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	SERVICE_ID BIGINT NOT NULL,
	NAME VARCHAR(255) UNIQUE NOT NULL,
	ANTWORT VARCHAR(5000),
	ANTWORT_VORSCHAU VARCHAR(255),
	VORGEHENSWEISE_UND_DETAIL VARCHAR(5000),
	ZUSTAENDIGE_STELLEN VARCHAR(2000),
	ZIELGRUPPE VARCHAR(2000),
	MEHR_INFOS VARCHAR(2000),
	FRISTEN VARCHAR(2000)
	
);